{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "%matplotlib inline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/tillbergmann/anaconda3/lib/python3.5/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.\n",
      "  warnings.warn(self.msg_depr % (key, alt_key))\n"
     ]
    }
   ],
   "source": [
    "np.random.seed(0)\n",
    "plt.rc('text', usetex=True)\n",
    "plt.rcParams['text.latex.preamble']=[r\"\\usepackage{amsmath}\"]\n",
    "plt.rcParams['text.latex.preamble'] = [r'\\boldmath']\n",
    "\n",
    "sns.set_context('paper', font_scale=2)\n",
    "sns.set_palette('Dark2')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Data Generation\n",
    "\n",
    "We first generate same documents, using the examples in Steyvers & Griffits, 2007."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "vocab = [\"money\",\n",
    "        \"loan\",\n",
    "        \"bank\",\n",
    "        \"river\",\n",
    "        \"stream\"]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "We use two topics, where the term distributions are different, and then generate some documents from those distributions:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "z_1 = np.array([1/3, 1/3, 1/3, .0, .0])\n",
    "z_2 = np.array([.0, .0,1/3, 1/3, 1/3])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 0.33333333,  0.        ],\n",
       "       [ 0.33333333,  0.        ],\n",
       "       [ 0.33333333,  0.33333333],\n",
       "       [ 0.        ,  0.33333333],\n",
       "       [ 0.        ,  0.33333333]])"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "phi_actual = np.array([z_1, z_2]).T.reshape(len(z_2), 2)\n",
    "phi_actual"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# number of documents\n",
    "D = 16\n",
    "# mean word length of documents\n",
    "mean_length = 10\n",
    "# sample a length for each document using Poisson\n",
    "len_doc = np.random.poisson(mean_length, size=D)\n",
    "# fix number of topics\n",
    "T = 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "docs = []\n",
    "orig_topics = []\n",
    "for i in range(D):\n",
    "    z = np.random.randint(0, 2)\n",
    "    if z == 0:\n",
    "        words = np.random.choice(vocab, size=(len_doc[i]),p=z_1).tolist()\n",
    "    else:\n",
    "        words = np.random.choice(vocab, size=(len_doc[i]),p=z_2).tolist()\n",
    "    orig_topics.append(z)\n",
    "    docs.append(words)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "The documents generated by the above procedure:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "loan bank loan money money loan bank loan loan bank.\n",
      "money loan money money money loan money money loan bank money.\n",
      "bank bank bank loan money loan money loan bank.\n",
      "bank bank bank river bank stream river bank river.\n",
      "stream bank bank bank stream river stream bank river river bank river bank river stream bank river stream.\n",
      "river river bank stream river stream stream bank stream river stream river stream.\n",
      "river river river bank.\n",
      "loan loan money money loan money loan loan money money.\n",
      "river river bank stream bank bank bank bank stream bank.\n",
      "stream bank stream stream stream bank stream bank.\n",
      "bank stream stream river bank bank stream river river bank.\n",
      "stream stream bank river stream bank river bank bank bank stream.\n",
      "stream stream river river stream river bank stream stream bank stream stream stream stream river bank.\n",
      "money bank bank loan money money money loan money.\n",
      "bank loan loan bank bank loan bank loan bank loan loan bank.\n",
      "money bank money loan loan bank loan bank money bank money bank.\n"
     ]
    }
   ],
   "source": [
    "for doc in docs:\n",
    "    print(\" \".join(doc)+'.',)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0]"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# topics we drew the words from \n",
    "# (in actual LDA this  would be a mixture of topics)\n",
    "orig_topics"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Init variables"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "First we initialize all our variables.\n",
    "\n",
    "Here is what we need:\n",
    "\n",
    "* i = just an index for all tokens\n",
    "* w_i = index pointing to the raw word in the vocab\n",
    "* d_i = index that tells you which document i belongs to \n",
    "* z_i = index that tells you what the topic assignment is for i"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "w_i = []\n",
    "i = []\n",
    "d_i = []\n",
    "z_i = []\n",
    "counter = 0\n",
    "\n",
    "# go through each document\n",
    "for doc_idx, doc in enumerate(docs):\n",
    "    # go through each word in doc\n",
    "    for word_idx, word in enumerate(doc):\n",
    "        # pointer to word in vocab\n",
    "        w_i.append(np.where(np.array(vocab)==word)[0][0])\n",
    "        # counter\n",
    "        i.append(counter)\n",
    "        # pointer to which document it belongs to\n",
    "        d_i.append(doc_idx)\n",
    "        # initialize some topic assignment\n",
    "        z_i.append(np.random.randint(0, T))\n",
    "        counter += 1\n",
    "\n",
    "# convert everything to numpy\n",
    "w_i = np.array(w_i)\n",
    "d_i = np.array(d_i)\n",
    "z_i = np.array(z_i)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Then we can initialize our count matrices $C^{WT}$ and $C^{DT}$:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "WT = np.zeros((len(vocab),T))\n",
    "for idx, word_ in enumerate(vocab):\n",
    "    topics = z_i[np.where(w_i == idx)]\n",
    "    for t in range(T):\n",
    "        WT[idx,t] = sum(topics == t)\n",
    "        \n",
    "\n",
    "DT = np.zeros((D,T))\n",
    "for idx, doc_ in enumerate(range(D)):\n",
    "    topics = z_i[np.where(d_i == idx)]\n",
    "    for t in range(T):\n",
    "        DT[idx,t] = sum(topics == t)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 11.,  14.],\n",
       "       [ 20.,   7.],\n",
       "       [ 29.,  28.],\n",
       "       [ 11.,  17.],\n",
       "       [ 18.,  17.]])"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# distribution for each word\n",
    "WT_orig = WT.copy()\n",
    "WT_orig"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[  8.,   2.],\n",
       "       [  6.,   5.],\n",
       "       [  3.,   6.],\n",
       "       [  5.,   4.],\n",
       "       [  8.,  10.],\n",
       "       [  8.,   5.],\n",
       "       [  2.,   2.],\n",
       "       [  7.,   3.],\n",
       "       [  4.,   6.],\n",
       "       [  6.,   2.],\n",
       "       [  5.,   5.],\n",
       "       [  2.,   9.],\n",
       "       [  8.,   8.],\n",
       "       [  6.,   3.],\n",
       "       [  5.,   7.],\n",
       "       [  6.,   6.]])"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# distributioni for each document\n",
    "DT_orig = DT.copy()\n",
    "DT"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Gibbs sampling\n",
    "\n",
    "We can now run `iters` Gibbs iterations. In each step, we cycle through each word token, and update its topic assignment $z_i$ given the formula in Steyvers."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "phi_1 = np.zeros((len(vocab),100))\n",
    "phi_2 = np.zeros((len(vocab),100))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "iters = 100\n",
    "beta = 1.\n",
    "alpha = 1.\n",
    "\n",
    "for step in range(iters):\n",
    "    for current in i:\n",
    "        # get indices\n",
    "        doc_idx = d_i[current]\n",
    "        w_idx = w_i[current]\n",
    "        \n",
    "        # get slice of WT and DT\n",
    "        tmp_WT = WT[w_idx,:]\n",
    "        tmp_DT = DT[doc_idx,:]\n",
    "        \n",
    "        # decrease count matrices\n",
    "        DT[doc_idx,z_i[current]] -= 1\n",
    "        WT[w_idx,z_i[current]] -= 1\n",
    "        \n",
    "        # calculate new assignment \n",
    "        prob_word =  (WT[w_idx,:] + beta) / (WT[:,:].sum(axis=0) + len(vocab)* beta)\n",
    "        prob_document = (DT[doc_idx,:] + alpha) / (DT.sum(axis=0) + D*alpha)\n",
    "        prob = prob_word * prob_document\n",
    "        #update z_i\n",
    "        z_i[current] = np.random.choice([0,1], 1, p=prob/prob.sum())[0]\n",
    "#         z_i[current] = np.random.multinomial(1, prob/prob.sum()).argmax()\n",
    "        # update count matrices\n",
    "        DT[doc_idx,z_i[current]] += 1\n",
    "        WT[w_idx,z_i[current]] += 1\n",
    "        \n",
    "        # track phi\n",
    "        phi  = WT/(WT.sum(axis=0))\n",
    "        phi_1[:,step] = phi[:,0]\n",
    "        phi_2[:,step] = phi[:,1]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Examine final count matrices"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {
    "collapsed": false,
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 10.,   0.],\n",
       "       [ 11.,   0.],\n",
       "       [  9.,   0.],\n",
       "       [  1.,   8.],\n",
       "       [  1.,  17.],\n",
       "       [  0.,  13.],\n",
       "       [  1.,   3.],\n",
       "       [ 10.,   0.],\n",
       "       [  2.,   8.],\n",
       "       [  0.,   8.],\n",
       "       [  0.,  10.],\n",
       "       [  1.,  10.],\n",
       "       [  0.,  16.],\n",
       "       [  9.,   0.],\n",
       "       [ 12.,   0.],\n",
       "       [ 12.,   0.]])"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# New counts:\n",
    "DT"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 25.,   0.],\n",
       "       [ 27.,   0.],\n",
       "       [ 27.,  30.],\n",
       "       [  0.,  28.],\n",
       "       [  0.,  35.]])"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "WT"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Calculate posteriors\n",
    "\n",
    "Now we can use the other formulaes to calculate posteriors $\\phi$ and $\\theta$. First, let's calculate phi and and theta:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 0.3164557 ,  0.        ],\n",
       "       [ 0.34177215,  0.        ],\n",
       "       [ 0.34177215,  0.32258065],\n",
       "       [ 0.        ,  0.30107527],\n",
       "       [ 0.        ,  0.37634409]])"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "phi  = WT/(WT.sum(axis=0))\n",
    "phi"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 1.        ,  0.        ],\n",
       "       [ 1.        ,  0.        ],\n",
       "       [ 1.        ,  0.        ],\n",
       "       [ 0.12827586,  0.87172414],\n",
       "       [ 0.06476323,  0.93523677],\n",
       "       [ 0.        ,  1.        ],\n",
       "       [ 0.28181818,  0.71818182],\n",
       "       [ 1.        ,  0.        ],\n",
       "       [ 0.22738386,  0.77261614],\n",
       "       [ 0.        ,  1.        ],\n",
       "       [ 0.        ,  1.        ],\n",
       "       [ 0.10532276,  0.89467724],\n",
       "       [ 0.        ,  1.        ],\n",
       "       [ 1.        ,  0.        ],\n",
       "       [ 1.        ,  0.        ],\n",
       "       [ 1.        ,  0.        ]])"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "theta  = DT/(DT.sum(axis=0))\n",
    "theta = theta/np.sum(theta, axis=1).reshape(16,1)\n",
    "theta"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([ True,  True,  True,  True,  True,  True,  True,  True,  True,\n",
       "        True,  True,  True,  True,  True,  True,  True], dtype=bool)"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Topics assigned to documents get the original document\n",
    "np.argmax(theta, axis=1) == orig_topics"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Plot Results\n",
    "\n",
    "We can also plot these results. The first plot shows the probability of a word assigned to a topic over iterations. The first 20 iterations here are plotted, and we can see that the distributions settle relatively quickly around their final probabilities.\n",
    "\n",
    "The second plot shows a visualization of $\\phi$. The original, generated $\\phi$ matrix is shown, then the matrix at the beginning of the Gibbs sampling (which is random), and then $\\phi$ after running Gibbs. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAjgAAADQCAYAAAAK/RswAAAABHNCSVQICAgIfAhkiAAAAAlwSFlz\nAAALEgAACxIB0t1+/AAAIABJREFUeJzsnXd8FVX6/9+3pdz0XkgnySSEQEjoRboIKChF7IqrWFa3\nfNe6/nbdddcV17J2xYaKhSqiSJUmvQQChIRJL6T3dm9y2/z+uCEESCAJCQk479frviaZcuace2fO\nfOY5z/MchSRJyMjIyMjIyMhcTyh7uwIyMjIyMjIyMt2NLHBkZGRkZGRkrjtkgSMjIyMjIyNz3SEL\nHBkZGRkZGZnrDlngyMjIyMjIyFx3qHu7AjLXD4IgzAVWdXD3JaIoPtZN530GGCqK4u3dUV5zmXMB\nN1EUP+2uMmVkfutcD31Ec1mLAHfgCPCIKIrZV1quTPcjCxyZ7mQrMO+CdX8FhjSvV7Raf7QbzzsF\niO+OggRBCAXmA4uxdmIyMjLdxzXdRzSLm2eBZ7DW9VkgUxCEMFEUc660fJnuRSHnwZHpSQRB2AIk\niKLo0dt1uRyCIDwMLAEygTCsb2ayBUdGpge5xvoICzBEFMXjzf+7ANnAVlEUF/Rq5WQuQvbBkZE5\nxwrAVRTFCM5/k5SRkfmN0yxmEs+KGwBRFGuAlVgtRDJ9DHmISkamGVEUa3u7DjIyMn0TURRrBEGY\n3MamasD1atdH5vLIAkemVxEEYQpWf5d4IBF4ThTFba22LwEmA48ArzbvdxSYf9ax7+w+oiiGX1Du\nM1jfrLKAX4BnZBEjI3Nt0Zf6iHa2hdG9/kIy3YQ8RCXTawiCsAjY0vyZgrWD2SoIwpxWu0lAKNaO\n6CPOdWBbLtinxZlMEIR5zdsrsTouLgYSsHZEMjIy1wh9vY8QBMG1+fjlnTlO5uogW3BkeoXm8ezF\nwNOiKL7RvHq7IAgK4BPg+1a7V4uiOK3VsZXAYkEQJomiuL2N4j8GVoqieEerdbKzsIzMNcQ10kes\nAo60qp9MH0K24Mj0FsMAF6wdVWuWAG6CIExq70BRFF/D6gR8UdinIAjxzeW+0n1VlZGR6QX6dB/R\nHDIegnV4TKYPIgscmd5iCFw8pt0qYdblTMXVQFthpaHNSznxlozMtU2f7SOah7ieBeJFUazrajky\nPYsscGR6iywAQRBCWq8UBOFsp5V5meNdgfJ2ylUg+9vIyFzr9Mk+otkCtARZ3PR5ZIEj01v8grWT\neeSC9c9idQZMbLXuvBDMZtOw1FzGeYiieAzrm9uF5Z4d05eRkbk26HN9RLO4+gWYJIpi7uWbINOb\nyE7GMr1Cc06JR4CPBEFww5rC/UbgIWDRhWZpQRBWYHUMvBF4GtjSOuHWBTwMrGx2RtwK9Aduxxph\ncUlHQkEQhnAuyV//5v+r5blmZGSuLn20j9ja/BkuCMLwC+p7oa+QTC8jW3BkrgZtzgfS3CHMxxqe\nuRKrQ+AUURQ/u2DXaqxZhpdg7dw+EkXxpvbOIYriGmBqq3IfxhoSuvJSlWxO4pUIHG4u7xmsk+l9\ndNkWysjIXAl9vo9otu6EYA0L/+jCjyAIzh1op8xVRJ6LSqZPIwjCR1gTdvX5eWpkZGSuPnIfIdMe\nsgVHRkZGRkZG5rpDFjgyMjIyMjIy1x2ywJG5FpDHUWVkZC6F3EfIXMRv0gdHEAQ1EACcEUXR1Nv1\nkZGR6XvI/YSMzLXNb9WCEwBkb9u2zci5Sdiuu09OTk6v10Fun9y+S3z6Otd9P3G9X2Ny+66LT5f5\nrQqc3wR6vb63q9CjyO2TkbkyrvdrTG7fbxtZ4MjIyMjIyMhcd8gCR0ZGRkZGRua6QxY4MjIyMjIy\nMtcdssCRkZGRkZGRue6QBY6MjIyMjIzMdUevzSYuCEI8sAiowjrV/cfN09jLyMjIyMjIyFwRvWLB\nEQRhCtZZml8RRfF5rFPcJwqCENfJcuIFQcjoiTrKyMjIyMjIXLv01hDVEiBRFMVcgGbLTRbwSUcL\nEATBFdgGuPVIDWVkZGRkZGSuWa66wBEEwQUIBSov2FQNxHeiqI+5wiyHMjIyMjIyMtcnvWHBGdq8\nrL5gfSVAR4apBEFYDDzDxSJJRkZGRkZGRqZXo6i6JE4EQXgYOCSKYk73VkdGRkama9TVNaHXG3u7\nGjIyMq3oTYHj3tkDBEEYAoSJovh9D9RHRkZGptOkiWW89p8dfLbkIBaLPGp+rSJJ8m93vdEbYeJZ\nzUvXC9a7X7D9PJp9d54XRfH2zpxMEIRFWMPRW2MDkJGRQV1dXWeKu6ZobGwkNTW1t6vRY8jtu7aJ\njo7u7Sq00NV+QkytZf+eMtzcbcjLrWbjz4cJC3fq4dp2H9f7NdaR9tXXmzh6uIL8PB0zbumHm7vN\nVardlXO9/35wZf2EojdUqyAIlUCmKIrDWq3LACRRFCNarZsriuKa5r8fBuZxzndH0fy/BKwGloii\nuL2D5w8Bsrdt20ZAQEA3tKhvkpqa2qceIt1NR9snmU2gUKJQXlt5La/33w/rPdxnuVQ/YbFIbPgp\nlV93ZjFydDCz58Tw1dJEigpqePr5iWhsVL1S585yvV9jl2pfY6OJndsz+HVnFrY2atQaJa6u9jz2\n5GiUyj59abZwvf9+zXT5x+itRH+vAIsFQXAWRbFWEIQwrJFVLW9QgiB8BCwSBGGJKIqPiaL4CReE\nkQuCYAGqRVFccDUrL9P3MVYV0nByMw3Jm2k49QsqR0+CntmCxiOot6smc41jaDLx3dfHSDlVws2z\nBzBufCgKhYKZs6J589Vd/Lori8lTIy5fkEyvYDZbOHwwny2b0mjUGxl7QygTp4RTWFDDkvcPcGBf\nLqPHhvR2NWW6gV4ROKIoviYIggSsEgQhG0gAFomi+Fmr3bYC87EmBDwPQRCeBoZhtd64CoKwgk5Y\ncGSuPySTAV3GPquoObmZpvwTANiFDMVt0qPU7P+WvP/eSPDzO1C7+vVybWWuVWpqGvni08OUltZz\n34NDiRno27LN29uRUWOC2fFLBsOGB+LsYteLNZVpC/F0KT//mEpxUR2Dh/gz/eYo3N21APQP92TY\niEA2rj/NgIE+uLra93JtZa6UXpuqQRTF14HXL7F9DbCmnW2v9VS9ZK4hagqp2rGbhuTN6FK2Y2ms\nQ+XoicPAG3G/6S84DJyK2tkbAJexD5C3eCJ5r00j6NltqJ29ernyMtcahQU1LP3kMBISjz0xmoBA\nl4v2mTotkqOJBWzeKDL/jsG9UMuOYWgy8fWXR2lsaiAkJBx7e01vV6lHKS6qZf2PqaSdLiM4xI0n\n/jSGoOCLc8TOnBVNakopP6xJ5v4Hh6JQXBtDVTJt02sCR0amq1iadBS8OxfFqa2UKJTYhw3Hffpf\ncBg4DbuQeBTKi/0fbHzCCXx6C3mLJ5H/xgyCnt2KSnuhn7uMTNuknCrh26+O4unlwMKHhuHSztu9\n1sGGqTdG8NO6FMaMC8G/38UiqLcxGMws/fQw+XnVSJLEO2/u5r6FQ/Hzd+7xc0uSRLW+mJyK4+RW\nniCn4jiFNSI+TmEM8LuBGL/xBLjFoFR0j7+cXmdizcoTHDqQh5ublnvujyd2sF+7wkWrtWH2bTF8\n89VRTh4vYlCcf7fUQ6Z3kAWOzDWFZDJS8OEd6NL3Is14mcjpD6Ny7FjGAVv/aAKf2kTeq5PJf3Mm\ngX/ZhMr+2ol4aQ9TbSmN2UdwiJmCQn3tRIBcKxw5mM/+vRVEDfDhrnuHYGt76W5z5JgQ9u3N5acf\nUlj0+Mg+ZQUwGs18+dlh8nKreHDRCMrKzrBvdzXvvbWHuQsGEZ/QvUEX9U1V5FYcJ6fynKCpbSwD\nwMnWkxCPQYwKnU9hzWk2nnqPdSdew8nWg2jfccT4jSfa7wac7Ty7dO7jxwpZvSIPtUrFjFuiGTMu\nBLX68s7fg+L8OHrEm3XfnyI80hOtVr6nrlVkgSNzzSBZLBQtXURD8hYC/rCWfE1Ih8XNWeyCBhP4\nlw3kvzaNM2/PJvDP61Haanuoxj2Lqa6cyo2vU7XtAySDDrVHMJ63/BWXMfehUF/fQw5Xk1+2pDNt\negIzZw3oUHSNWq1k5qxovvzsCCnJJcTE+l72mKuByWTmq8+PkJ1dycKHhtM/3AODsZQn/jiG1StP\nsPzrJPJyqrh5dgxqddcsKJIkIZbsY2/WcrIrkiivzwPATuNEsHsso0LnEewxiBD3wbhp/c8Tf0Zz\nE5llRzhVtIuU4l85lPsDAIFuMQzwHU+M/3jCPOJRqy4vOAoLaljxXRL+/bQs/N0YHBw7LlIUCgW3\nzYvl9Vd3suGn08xbMKiT38L5VFXpsbVRoXW4foSSJElU6YrIqzpJXuVJ9MZ6/Fwi6Oci4O8Sib1N\nz1sDO4IscK5DDMXpFHywACrOkK7u2E/sED0JrwWvonHr18O16zplq56jdt8y/BZ9heOg6dDF/A/2\nYcMJ+POP5L8xg4L35tHvD2tRamy7ubY9h7m+gspNb1L5y3sAuE15Ase4mVRteZviLx6h4ufFeNzy\nAi6j70Ghkm/xK+XGGZHcMjumU8cMiPEhPMKD9T+mIER7d1kwdBcmk4VlSxPJSK/ggYeGEhF5zipi\nY6vmznuGEBLqzk8/nOJMfg33PJDQKSdbSZJILtzOhlPvkl1xDD/nCGL9JxHsPpgQj0F4O4VddthJ\no7IlyncMUb5jmMtfqdGXkFK0m1NFu9iT+R2bUz/AVu3AiJDbmDXoLzjatv1yo9MZ+OrzRLy8HBg/\nybNT4uYsrm72TJ8Rxbq1pxiS0I/+4R7ntfVQzlqUSjVBbgPxcgppt22pKSV8/eVRHLQaHlw0Al+/\nti3GJrOBotp08iqTqW+qwsXeC2c7b1y1PrjYeaO1cbkiS+DJ40VsWJ+KSqnEw1OLh6fDeUt3dy0q\nVdttkCSJSl0BeZUnya08SV5lMvlVydQ1VQDgaOuOvcaZnelfIkkWANy0/vRzFfB3OfuJxM8lHI3q\n6jre90oenN7mes6DYyzPJfeVCSg0dhjCp+LldXlnWsnYSPWuz5BMjXje+g/cpjzR5x6MFRtfp2zl\nc3jf8Tru0/4EXHkOiIZTWznz1mwcYm+i3+Mr+pzV48L2mRuqqNz8P6q2votkMeM2+THcb3rqPIfp\nxrzjlK97ifqj69B498dz1v/DeeSdfe73bKbvjN20wZX2E4UFtbz9xq/NoeRh3V6/jmI2W/j6y0RO\np5Ry34NDiR7g07LtwmssN6eKr79IxGSycNd98ecJobawSBaO5W9k06n3yK9OIdRjCNNjniDWf3K3\nDs1ZLGbyqpI5UfAL29OWolQomRX7F8aF341KqW61n8QXnx0mJ6uSP/5lHKVleV3uIywWiQ/e2YtO\nZ+TPT9+ARmMd3tpw6l1+PHEuPsZW7UCg2wAC3QYS5DaQIPeB+DqHc+RgAWtXJxMpeFFdrae6Ss99\nDw4lKNSRgupU8qqSya86RV5VMoXVIiaLoaW8JlPDeXVRK21xtvfCxc4LF3tvXOx9cLH3pqlGxU1D\n72nXYtLQYGDd98kkHS0kKtobdw8tFeUNVFToqKzQtWTeVioVuLra4+Gpxc3DDqNzKjWKFKqMaZTp\nRXSmKsA6rBjkbm1jkFsswe6xLZY4g6mR4tp0CmvSKKg+TWGNSGFNGlW6IgAUCiXejqEIPqO4Y+i/\nOuNn1eULSRY415HAMVYVkvfKBJAsBD2/k4ySug7f3Ob6Ssq+/xvVOz/GNiAWn3vfRRsxpmcr3EFq\n9nxF0WcP4j7jGbzn/6dlfXckuapL+omC9+bjlDAH/0eWtemgfCksxqYes/6cbZ9ZV03llrep2vI2\nksmA66RH8Zj+NGoXn3aPbcw5ahU6SevR+ETgOftvOI9Y0On29TDXtcABWL3iOCePF/PMCxNx6IUh\nCrPZwrfLjnHqZDH3Lkw4L6wd2r6H6uua+HbZUTIzKpg2I4oJk/pfNDRntpg4nPsjm1Leo7g2k0jv\nkcyIeRLBZ0yP+xzV6EtZe/xVDmSvJsB1AAsS/kmE93AAtm1JZ/NGkQd+N4wBA32uuI8oLqrl7Td2\nM2FSONNmCBw/s5UPdz/EjJgnmRBxP/lVp1pESl5VcsuQnBIbqPfD3ymasfHjaDTo+fXIr1RbMpDs\nS5Awo1Ao8XOOIMhtIIFuMQS5DyTAbQD2GieaTDpq9KXWT2MpNboS67J5XW3z3w2GajQqW+ICpjEq\ndD5RPmNQNt/jp5KLWbPyJCajmdlzBhI/tN95v43ZbKG6Sk9FhY6K8gZySlNJr9tIiXInZlUNCoMT\nKl0QyoYgVA2BqBqCUFvc0GptcdBq0DrYoHXQoNXa4OJqh6+vE77+znh6Opx3vTQYaiiqSaOwWqSg\n5jQWi5m7hv2nM9eJLHA6w/UocEy1ZeS9OgmLvpag53Zg4x3WpZtbn3WYkmVP0JiTiMvY+/Gav7hX\nQ6rrk9Zz5t25uIy5D9+FH593U3RXFs/aw6sp/PAuXMbci+/CTy6Z8dhYVYg+bQ+6tN3o0/bQdOYk\nao8gtJHj0EaOxV4Yh42v0C2dfGrSYbzyNlO5+S0kgx7XiY/gMePpTuXx0WcdpnzdSzSc2IiNXxSe\ns/+G07B5fUXoXPcCp662kVf/s4NhwwOZPWdgt9bvcpjNFpZ/k8TJ40XcfX88sYMuvm7au4fMZgtb\nNors2JbJgIE+LLgrDnt7DUZzEwey17A55QPKG/KJ8ZvA9JgnCPcadlEZPU1WeSLLE18kr/Ikw4Jn\nE+f4CCu/yGbi5HBumhkFdE8fsXmDyI5tGdz1mD+fH7uHSJ+RPDrukzYtELW6Kr5Z+xOnzxzFN6KW\nJttcSmozUSk1+DlHYqr0oyrPnTFx45g1ZTK2mivz/zt0/FcqNcnsz1pNSV0mrva+xAfMpk6MRTyi\nQIj2Yt7tg9qN+mtoquZw7jr2Z68mt/IEWhsXhgXPZlToPLzto9HrjDQ0GKxLnQFdgxFdgwGdzkBD\ny99Gqqp06Bqsk82qNUp8fJzw9bN+/Pyc8fVzwsnZtqv9oixwOkNfETgVG9+g7tAqfO9/H7uQhC6X\nY26oIu/VKZiqCwl6fge2fld2c0sWM9U7P6Fs9QugVOI192Vcx//uqj8Udel7yX9tGg4xU+n3xKqL\nhlm6M015zd5lFH26ENdJj+FzzzsoFAokScJYmolO3I0+fQ+6tD0YSzMB0HiFoRXGYReSgKE4HV3a\nHpryk0CSUDl5YR8xBq1gFT22gYMvOURkaWrAWJGHsSIXU0V+89951Bz7CaWpEZfxD+Mx85kr8o/S\nZx6g/IeXaEjego3/AJwSbsU+Ygz24aNQ2feaQ+B1L3AAtm9NZ8umNP7vmfF4+zh26lhJkhDzklHY\nNmCWDBjNTRjNjRcvLU0YTI1YJBNDAqcT5jGUld8mcexoAXfdG8/gIW2HO1/uHjp1spgV3yZh7yQh\nTM7iUNFXVOuLGRI4nekDfk+Qe2yn2tPdWCxm9matZG3SYvSNevwNc3n23n9g02xV7Y4+wmg088ab\nGyn0fwl3dyeevfEH7DUX+9Lo9UaWLU0kO6uC+XcObolIM5j0KBUq1CobJEli8waR7b9ktEzx0Z7v\nS0c42z5JksiuOMaGo19xqnQTkkqPl20MU2LvZGjwLBxszqUrMFtMnCraxYHs1Zwo+AWLZCbGbzwj\nQ+cxqN8UNKrOW6QlSaK+romiojqKi+ooLqqlqLCOkpI6TEarX47WQYOvnzPhER5MmhLRmekwZIHT\nGfqCwDHVFJP5TCQKpRKLsRHP2X/HY8YznfaVMOtryX99GoaSDIKe3YZd4DmP/yu9uU01JZSutDr2\n2oUOxfe+zgmxsxe9o1PnlXvTmWRyX5mAbcBAAv+yEaXNuTcQo8XMPw6u52RRDhHe/vhqXfBzcMHv\n7NLBBVcb+06fs2rHx5R89TjOI+9EMpvQpe3GXFMMgG1ALPaRY9FGjsM+ciwat4sfGGZdDfqMfS0W\nnsbsI0gmA0o7J+zDR2EfORaF2hZT5VkRk4+xIhdLQ+W5QhQK1C5+qD0C0bv0J/yul9F4BHaqHZdC\nl76Pyk1vohN/tZ5XocQ2cJBVkEWMxj5iDBr3q3ZP/CYEjtFg5rXFO/Hzc2Lhw8M7dIwkSZxOLWXl\nzs8oclvS7n4alR0alW3L0mQ2UK0vxotR6E/cyN3zpjEkoX1hfLk+wmhuYtPxL9iU8j5mZS3O+tGM\nCXiQcUNH4+7RN6IPTSYz7723lTM2K2hw24m3Uwi3x79IjP+EbhE4FouZ/268i5zK48zu9wnTJ427\naJ/qaj2ff3yoxc8mPOLSvksH9uXyw5pkhCgv7r4vHpvLpB5oj7Pt0+uNrF+XwuGD+fSPdCZqfBkn\nSteRUrwblULD4ICpxAfOILviGIdyfqC2sQx/F4FRofMYHnIrLvbeXTr/5bBYJMrLGygurG0WPnWY\nLRIP/K5TSRRlgdMZ+oLAKf76j9TuW0bYf05RufVdKje+hl3YcPwf/hIbn/AOlWFp0pH/5gya8o4T\n+PQW7MPONxN3l4VDJ/5K8bInMRSm4DrxUbzmvITK4eIsoOcdozOw6rvjnEouwcNTy8BYXwYO8iMw\nyPWyyt1Ynkvuy+NQOXoQ9PyO8xLyGS1mfr/zO7bkpTDU1R+9CooaaijT1yNx7lq2V2vOCR6tC0O8\nArlLGI7mMlaoyi3vUL72RWz6DbAOOUWORRs+ptPh6AAWg57G7MNWC1DaHvSZ+5EsZjTuQWg8glB7\nBKHxCETjEYzaI9C63j2gJZdNR3+/Mn0dJysKGePXH9sOCmTJYsFQLKJP34subS/69L0Yy7IAUHsE\no40Yg32z4LH1i+opB+zfhMABSDpawLfLjvHwoyOIEC495JuRXs7mDSI5+YXoh7xEgHMcgvp+CvN1\nFOTpMDYqUSttCQzypH+YJ6H93QkOccPWVo3JZOKD1e+Q2vQl2NQxPuIeZg78I052Hm2eq90hKouJ\nA9mr+Tn5Hap0hQwNmk246i5yU1ScTi3FZLIQGOTKoDg/Bg32w82998TOmpUnOHLoDI89OQqlcxHL\nE18ko+wQg/pNJd75LkbGTbqy8o/9h1/ET4jjRfKTfHjq2Qm4up174SoqrOXzjw+hUMCDi4bj69cx\ni+jZCCtfX0ceeGg4Tk6dt5ykpqaiUnqyevlxdDojN88ewIhRQS3ioUpXzKGctezPXkVxbSYONq4M\nD7mVUaHzCHQb2KdyNF0CWeB0ht4WOIaybLKeH4DnrP+H56wXANCl7aHo04WYakrwvuN1XCc8fMmL\nz2JsouDtW9Gl7yHwLxvQRl78VtGdQziSyUjl1ncoX/cSkqkJu8A47MNHYt9/JHbhI9F4BLfUNz+v\nmq+/TESvMzL1pkiKi+o4lVyMrsGIs4tti9gJDXO/yDxrqi0j75XxSCYDwS/sPs/fxGQx8+SuFWzI\nTeajiXcRolO1tM9gNlGqr6Ooocb60Z1d1lJQX83x8jOEu3jx0shbGOd/6YkQJUnqkRtfslhAoehw\n2Zf7/XLrKvg4eTfL04/QZDbho3VmUcxY7hZG4NgFx2dTdRG69H3o062CpzEvCSxmUChRu/iidg9A\n4x6I2r1f8zIQjXsAarcA1K5+XRnC7NO9a3f2E5Ik8f7bezEYzPzpqRvaFPm5OVVs3iCSkV6Ofz9n\n7AdvILlqLf+cuR13B6sVxmy2UFhQS3ZWJdmZFWRnVaLTGVEqFfQLcMHeXkOaWMZtt0dS7byFzSkf\ngkLBTdGPMUn4HTbq88N0L7zGLJKFI7k/sj75LUrrshkSOJ1bYv8Pf5fIln0aG42knirlRFIhp1PL\nMJstBAW7MijOn0GD/c57+Pc0Rw7ls/K749w2L5ZRY4IB63d9JPdHVie9TENjNbcNeY6JkQ90KTvy\nwZy1LN3/J+bGvcDYkIW8/spOAgJdeOChYSgUCtLTylm29Ahu7vY8+PDwdn1d2iM/r5qlnxzCxkbN\n7x4Zjpd3x4Yw9XojxUV1bNuaTNrpWsLCPbj9jsHtWtUkSaK0Pgd3rX+XhqB6GVngdIbeFjiFnyyk\nIXkzG+5awpozIq+MupUx/uGY9XWUfvcXanZ/jsOg6fg9+Alql4uThEkmIwXv305D8mYC/rQOh5ip\n57ZJEsvTj/Da0S34qLXcPXA0M0MG4mbn0C11N1YVUJe4lsaMA+gzD2AszwFA5eKLXdgIUm2msz3d\nFz8/J+55YCgentbzms0WcrIrST5RTPKJYmpqGtFqNQwY6MvAQb5ERHqiNOnI/+9UjBW5BP/1V2x8\nzwkRs8XCH3avYH32Sd4ffwc3hw7qlIA7WV7A/zuwjsSyPGaGxPL3YTPp59i3p2por30plYW8f3IX\nP2WfwMXGnoXRoxnfL4KvxYOszUzCQWPDA9GjeXDAaDzsOufz0RpLYz36rIMYSjIwVZ7BWHnGOrxW\neQZT1RkkY+O5nZUq1K7+uE18BI+bn+voKX4zAgesAub9t/cyZ34sI0cHt6wvLKhh8waR1JRSvH0c\nmTZdwD2ojpc3T+fmgX9kxsA/tFumxSJRWlJHVmYl2VmVFBXUMm5iGCNGBgFQ21jOz8lvszvjW1zs\nvZgV+xQjQue0POxb+3AkndnMTyffpLBGZKD/RG6J/QvBl/Gx0euNpJ4q4XhSEWmnSzGbJYJD3IiL\n92fEqKAOZQ7uKoUFNbz39l4GD/bn9rsGX/Ti0Gis5/Odz3KifD0RXiO4b8RreDkFt1PaxeRWnOD1\nbfOID5zBAyP/h0Kh4ERSIV9/eZS774vHZLKwavlx+od7cO/CBOzsumblrKzQ8dnHB2moN/DA74YR\nEnbOWmw2Wygrrbf6thTWtvi4VFfpAVCrFcycNYBRY0I649NyrSELnM7QmwKn6Uwy2X8fgu2cl5lS\nWYuTxo7yxnrujxrJX4dOx0FjS92xnyheuggkCz73f4jz0Dktx0sWM4VL7qUu8Xv6PbEKp7hbWrYV\n1lfz9L7v2VWQxs0hsRRUlpNUW4xKoWBCQCS3hsVxY+AAtJruC1c11RSjzzxI9elDbDjhTmaTQHTT\nzww3LMMhcCC2QYNRqM9/Y5AkKNa5kF7tTUa1N9VNDmiUJoLVIsNrPyDq2e/P8/UxWyz8355VrM1K\n4t0b7mBdHshLAAAgAElEQVR2mHUSw85aqCyShe8zj/HykY3UGZr4w+CJLIoZh10fy39zltbtkySJ\ngyXZvH9iFzsKRPwdXHhk4A3cGTHsvN+zoL6aj0/t5tu0Q0gSLIgYyqMDxxHo1PkhtkshSRLm+gqr\n4Kk6YxVAFfnYh4/Cacgtly/ASp/ukXuin/h22VEy0sp55oWJ1NY0sWWTyImkItw9tEydFsmQhH4o\nFPD2jrspb8jnxRlbuyU5WkltFmuPLybpzGYCXQcwZ8gLRPuOJSUlBcm1lB9PvkFu5QkivUcya9BT\nXYqK0uuNpCSXcDypkLTTZXh6OTBvwSBCQrv32gPrEPg7b+zB1k7F7/84FhubtoVUamoqCrcKvjr4\nDPVNldwW9xzjI+67rDWnRl/K4i2zcLLz5KnJq1ssX5Ik8eXnR8hIL8fQZCZhWADzFgy6IkdhsOar\n+fKzw5zJr2HsDaHU1jRSVFRLaUk9ZrP1Ge3kZIufv/O56CR/ZyqrzhAb27kklNcgssDpDL0pcM68\nM4fGvON8MPMlfinKYvfcp1iVkcjixM142Tvy+th5jPHrj6m2lOKlj1Cf9BPOo+/F5+63UNo5Ubx0\nETV7v8L/0W9wHj4fOGe1eenQerRqGxaPvo2pQQNITU3FPbgfP2Wf4Ies4ySV52Ov1jAtKIbbwuK4\noV/EZX1SOkLBmRq+/jKR+joDc+fHILiX0Jh5EH3mAZoKToHF0u6xkgSVkg9ZpgGcNI0msr8j9/5+\nest2i2ThqT1rWJVxlLdvuJ05/Ye0bOvqEFytoZH/Jf3C5yn7CHB046URtzA5MKpTZUiSRHZtOSmV\nRQQ5uRPt7tct32VrUlNTEaIEfsk/zfsndpJYlkekqzePx45ndljcJc9X2djA0tR9LE3dT52hkVmh\ng3g8dgLR7n1j2oBmfnMCp6pKz2uv7MDT04GS4jqcXeyYPDWCYSMCWx6SR/M38PGex3hs3KcMDph6\nmRI7R0bZYdYce5nsimPE+I2nqracwoZThHoMYfagp7otj01RYS2rlh+n4EwNo8eGcNPMqMvO4dVR\nLkzmd9ZK3BYtTrjGOr4/9h92Z35LpPdI7hvxGp6OQW0eYzQ38b/td1Jen8fz037CTXt+eH11tZ4P\n39lHwrAApt4U2W3D2UajmVXLj5NyqqQlzNrPz5pbxs/Puc2MzN3phtCHkQVOZ+hJgVNf14Rao2zT\nXKnPPEDuv8diueMNphUW888RN/PgAGsyvezacp7as5qDJTkt1hyt2oaa3V9Q+t2fUTq4Y99/JHWH\nVuL3u89xGXsfcL7VZl7/eP4x4mZcm+dWuvDiz64tZ13WcdZmJZFZU4arrZabQ2K5NWwww33aTzfe\nHpIkcXB/Hj+uPYWXtwP33J/Q4THktti/N5e1q0/y5J/HEhjkikWy8Oy+tSxPO8KbY+cxP+L8CK4r\nvbnFqhL+dmAd+4qzmBIYxT+G30KIc9vOmPXGJpLK8jlalkdiaR5Hy/KoatK1bLdTaRjs2Y94r2AS\nvINI8A7C6wom8qw3NvH5/q38UJFGWnUp8V5BPDFoAlMCozr1OzUYm/gu7TBLkndTpKthckAUj8eO\nZ5hPcLfN2HwF/OYEDljDxvfuyWHipP6MGB3ckiEXrCHF//h5Mn4u4Twx/sue8QWTJBLzf+anE28i\nmRTMG/Z8t2ceBuvwyp5fs9m8UcTJ0ZY5t8ciRF15tM6FyfwuxYV9RErRryw79Cw6QzVz4v7KuPC7\nz7sPJEni68PPcSB7DX+e9F27lqye8tPrbNmywLnMgbLA6b6Oy2gw89orOzCbJRbcHUdkq2gJSZLI\n/+8UTLVlvDjuD2TVV7Hjtj9j0yrqxSJZ+Dxl30XWHENpFkWfLkSfvhefe9/FbdJj7VptWtPexS9J\nEqcqC1mbdZx1WUkU62px0tgyyDOAIV6BxHkGEucViK+2/WiApiYTa1aeIOloIcNHBjH7thg07ZiJ\nO4rZbOGt135F62DDI78fyV8PrONr8SCvj5nLHZEXdzTdcXNLksT6nJO8dOhnKhrreSx2PL+PnUCx\nrobE0jwSy/JILM1FrC7BIkk4qG0Y4mUVMPFeQcR4+JNbW9Gy39GyPMr09QAEOboT7x1EvFcgCd7B\nDHD3Q61QUmtobOUEXUNhs2N0cSvn6DpjEwAT+wn8ftB4RviEXlGHajCb+CEriQ9O7iKjpgwXGzvi\nvIIY4hXIEM9A4r0Cu81PqxP8JgXOpfjp5JtsSvmAv0/fgo9zz0/vcDUekOVlDaxeeYKsjArih/bj\nlltjupTV2WKROJVczNdfJJ6XzO9StNU+vaGW1UkvszdzOVE+Y7h3xH/xcLD+vjvTv2L5kb9x97DF\njAu/s9N1vNrIAucyB8oCpxvfzH7JYMtGkaBgV3Kyq7hhYhg3zYhCrVbSkLyF/DdmUHfXu9x2JpcP\nxt/JrGZfkgtp05qjUmMszcLGN+KSVpvWdOTit0gWDpfkcqA4i2Pl+SSVnaG80fqA9tU6E+cZaBU9\nXoEM8uiHk40dRYW1fP1lItXVjcydH0v80O77DlNTSlj6yWFUo80sq9/Pq6PncLfQdu6Q7ry5G4xN\nvHtiBysPHSW2MJj9AWnobJro7+JFglcQ8d5BJHgFE+nqjeoSmY4lSeJMfVWz4LFaek5VFGIxS4wu\nENAabSixr6HMoZZybR0GtQkve8eWkHbfVrl8tNV6pieM7pb2ncUiWdhblMmhkhyOleVzrCyfGoPV\nYTHEyYMhXoHENwufAe5+5wnwHuA3KXDO9rkXCtby+jz+8fMUJgkLmRP3fLed71JcrQekJEkcOpDH\nzz+molIrmT1nIIPj/C4r2uvqmkg7XYZ4upT0tHIa6g1ECl48uGh4h5xqL9W+5MIdfH3oOfTGOuYN\n+X94O4Xy9o57GBd+F3cO/VeX2nm1kQXOpemTM/Bdi9TXNbGjOTvlrNti2LUjk80bRDLTK7jznjh0\na/6GXegw/k9nZLBnADeHth+dEOrsyarpi1qsOdvPiLw+dh6jfcP5Lu1wi9Vm6eT7LrLadBalQskI\n31BG+IYC1o6ooKGapLJ8jpWfIaksn7eOb0NvMqK2qBjVEE5Anid2zmqm3h9OjNC9Ph1ClBdKH4nq\nIwZevm92u+Kmu3HQ2PJcwk24JDqTXV/JPWVjePiJEfi5ulz+4FYoFAoCndwJdHLn1rA4ABoMBj77\n4iAFtTXY+6vxK3fFWGb1S/LydiAk1J1gbzdCQt3x8nZo6fRTuzhb+qVQKpSM849oCZU/60t0tCyf\nY2V5HCvL56fsE5gkC7YqNTHu/oS7eOGrdcbXwQUfeyd8HVzw1Trjaed4SbEncw5Jb6TpQC5Nv2bR\n+GsWCrUS9yXzUIecc8BdfezfONi6MCPmyV6sac+gUCgYMSqYqGhvfliTzLdfHSXpqA+3zR14Xmi1\nyWQhN6eyWdSUUVhQC4CfvxNDhwUgRHsTGubeLRFDA/0n8vcZW1h19F98c/h5lAoV/b2GcXv836+4\nbJm+Qa8JHEEQ4oFFQBXgCnwsiuKxDhw3GZjfatWSjhzX0/yyJQ2FAqZMs6agnjg5nPAIT75ddpS3\nX9vJiDpX7ObP40R+Jitueviy/g9KhZKHYsYyOTCKp3av5vHvvyMKf/bZpzE3vH2rzZWiUCgIcHQj\nwNGNm0OtWZEbdE2s35ZC0r5CTE0WKnxr2emRytKDu9AcVhHl5stgzwAGefYjzjOASFcf1F1wuJUk\niX8f2cB65yRmlAyhf/mlx9e7m+oqPbliFaPHBnMssZAfv0nhd4+MQK2+sof4rs2ZnEmt4e77rCnz\nJUmiolxHbk4VOdmV5OZUceRQPpIEWq2GoBCr2LHXGrqpZe2jUCgIc/EizMWLeeHxAOhNRpIrClos\nPGJ1CbsK0ihrrMfSyuKrUijxsnfEV2sVPD5aZ2YExzDGv2OJKq93TAU1NO3KpOnXLJoO5UOTCVWA\nC3aTwmnan0vFwhV4LF2AOsSdlKLdJJ3ZzMKR/8NO03U/tr6Oi6s99z04lJPHi/hhTTJvvLqLaTOs\nc7eliWUt0UlaBw0RkV6MvSGUSMELZ5crjyRrC62NC/ePfJ34wOkczFnLgoR/olL2zahKmc7TKwJH\nEIQpwBYgVBTFXEEQhgCJgiDEi6KYdInj5gHPiaI4tPn/j5qPmyKK4varUvk2KC2t58C+PKZNF3B0\nPBcSHRjkyh//NJpvXlzMHu2TlB+oYdKQKMb49e9QuQ31BvKP1jI6OYr+xdZhoyljo3j4hu4dtmgP\nvd7Ivt057N6VRVOTiYRhgUyc3B8PTwf0JiMplYUcLz/D8fIzHCjO4hvxEBISdioNMe5+DPYMIMrd\nF5sOip3E0jyWiQf5x/ibcXF34pct6cQPC0CrvTqzMB/Yn4tao+SmmVHEDvbj048Osnr5cRbcHddl\n/5f9e3PZuT2TmbOiW+YDUigUeHo54OnlQMIw69CHXm8kL7eKnOwqcrOr2L41HbPZgoe7P5FRV3ey\nU3u1hmE+IQzzCTlvvclipkxfT4mulmJdbcuyWFdDia6O/cWZONvY/WYFjmSyYDxeSOOuTJp2ZWHK\nKAeVApv4AJyeGIPtDWGo+3ugUCgwl9VTsXAFFQtX4PLZHFamvkh/z6EMD7mtt5vR4ygUCgbF+dM/\nwpP161JY9/0plEoFQcGuTJwUTmSUF/0CXK5qXpfYfpOJ7Tf5qp1P5urQWxacJUCiKIq5AKIoHhME\nIQv4BLhUAobbgSGCIMQ1C6HE5vWPAL0mcDauT8XZ2ZaxN4RetK0x8VvGVPwbw8QvMBx3xO2QPdlR\nFYT2bztax2KRSBfLOHQwn5TkYiQJBgz0YcYt0aSL5ezfm0PhyFr8+/XcBIm6BgN7fs1mz6/ZGI0W\nho8MZMLkcNxaZSi1V2tI8A4mwftc4qw6QyMnKwo4UV7A8fIz/JJ/ms9T93X4vCqFkr8Nm8FDMWOp\nCWgk6Vgh27dmcPPsKxuG6wgmk5mD+/NIGBqAnZ2G/uGezL9zMMu/TsLNXcu0GUKny0w5VcIPa04y\nakwwN0y4tMOovb0GIcq7JcrEaDDzwXs7WfrpYe5bmEB0zNW1ZrWFWqlq8Q+SOZ/6Tw5Q//lhpNpG\nFK722I0LxfHRUdiODkHZhvVB5eWIx9IFVCxcwYa3nqVkVBbPT1t/raTO7xYcHGxYcFcck6aE4+hk\ni729bDmR6V6uusARBMEFCAUyLthUDcRf5vAlgNTKynN2QqRD3VfDzpGdWcGpkyUsuCvuoigii7GR\n8h9ewi5+Nh+qs5k8NQpP0YuP3t/PpKkRTLkxoiX3RWWFjsOH8kk8lE91dSPePo7cNDOKhKEBODbP\nURIe4UlGejnLvznGk38ee154aXfQUG/g111Z7Nudg9liYcTIICZM6t/h9ONONnaM9uvP6FYWqiaz\niY46sisVihanVhcXO8ZPDGPHL5mMGhN8yVwX3cGJ40U01BsYNSakZV18QgDVlXo2bRBxc7dn+Mi2\n82a0xZn8ar756ihRA3yYdVtMpx9cGhsVk2/04/CBBr5aeoS7709gYGyfymEj00zT4Xzq3tqN/dxY\ntHNi0cT6oehA4jeVlyPqjyaxa/tiElLi8B/lD92fE6/P4+npABYJydR+vqzWKK5wyFjmt0NvWHCG\nNi+rL1hfCdDKOnMRoihuA7Y17+cKPAccEUXxjR6q6yWxWCTW/5iCfz/nNmfsrd7+EabqQrZEvUBD\nUS5PjZ2K71Rntm1NZ9uWdDLSyhk+MohjiQVkpJdjY6Ni8BB/ho8MIijY9aKHokaj4o6743j3f3vY\nvEHsNstGfV0Tu3Zksn9vLhIwanQw4yeG4eR85ePeHZ38sS0mTOzPwf15bFx/mnse6Pgs5l1h3+4c\n+od74Ot3fu6aiVPCqazU8f2qk7i42nUoj0dlpY6lnxzGx8eRu+8d0uUspyqVgnsfSODbZUf5+otE\n7rp3CIPiLp7FvDfR643k5liH1XJzKgkN82DqTZGXP/A6QWo0UvP3TWji/HF58cYOCZvW/Jj/Lmqt\nPVNOTT7PJ+e3gCm3ioZvjqJfexJJZ+zwcTbDAnF5eTrqfrIlUebS9GYUVWVXDxQEYTEwBajAOmzV\nK5xIKiQ/r4ZFj4+8aLzYrK+lYv1ibEbeyZtFeSyMHt0y99GNNwlERHqx/OtjrFp+nOAQN+bfMYhB\ncf6Xzfbp38+FG6cLbPr5NNEx3vQP97yiNpSXNfDhe/toajIxZlwI4yaEnedH1JvY2Kq5aYbAquUn\nyMmu7JGU72C1tuTlVnNvGyJKoVBw27xYaqobWfZFIo8/ORr/S3SsOp2Bzz8+hFqjZOFDw7C5wuyt\narWSu++LZ/k3SXzz1VFMZgvxCVd//jSgxTn6rGN0TnYVpSV1VudoBw3BIe4EBP22Hjp17+/DXFSH\n27u3dVrcZJYd4UDOGu4c+m8Cx9/W4pNzPYscSZIwHMqnYVkiTTszUDjbob1zSIfbKzWZqP/0IOW3\nfYHz85Oxv7Xz1lGZ3w5XPQ9OcxTUVmCVKIoLWq3fAkwGEi7laHxBWU8DrwLPiKL4ejv7LMIardUa\nGyD2o4+W4OvbNd8Gs1ni+5V5uLraMHW638U77PkADn7KZ9Ne4md9HV8OmYPTBXMyGY0WmhrNODp1\nbuzZYpHYtL6Q+noTt84LaHcelsbGRuzs2rfC1Neb2PBjAUqlghm3+KN16HtZAywWiR+/P2OdVG52\nv/M6s8u1r6Ps2VlKQYGO+XcGt+vYaDRY2PBTAY16MzNvDcDR8eLvymyW2LKhkMoKAzNn98PV7cqc\no1u3z2KR2LOrlMz0esaO9yJC6DkfLLA+iHQ6M7U1RsrLmigtaaS0pJFGvRkAF1cN3j52ePvY4eNr\nh7OLptMPmujo6D7zZLpUP7FkyRJ8fC7uJ1SZ1Tg+v5fG+RE0ze+c1coimVmR9kckJO6IfAelQoWi\nqhHHF/ejaDRR/49RWPx7Ppqqu+6hy2IwY7O3ENufs1Hl1GIOcKRpZiiGGwLAtnND7YoGI/afJWPz\nawGG4b7oH4lFcmn7payn2qcsqMfio4XuHi7Tm1Dl1yE5aZCcbZG0arjEfXXVfr9e5Er6id54omU1\nLy+cytn9gu0XIQhCKFApimJN86rVWAXOq4IgfCyKYu2Fx4ii+DHw8QXlhADZJ5P0jHsysksz3u7a\nkUlDvYlFj425aFjDVFtG1tFlSGMeYFVDFc8n3MTw2LhOn+NS+PoE87/Xf+V0sokFdw9sc59LJYGq\nq2viw3f3odFoeOzJ0ec5EPc1bNRefPLRQQxNrsQNOTdE0x1JrhoaDGRnZzN5agQxMRGX3Dc4pD/v\nv7WH3TsqeezJ0ec5RUqSxPJvkigrNfDwYyMIa8eJvDNc2L7o6GjWrDzBnl35eHv7njcjdVcwmy1U\nVeqpqGigolxHRXkDFRU6KsoaqKjUYTJafSLUGiWBga6MGu1LcKg7wSFuXcpE25e5VD8RHh5+UaI/\nyWim/IVlEO6B33M3o+hkFu/dGd9Rqs/gqSmrCfc6d/+av42gYuEKXP995KpYcno6UZy5vAHdiiR0\nK5KwVOiwHRuKw/M3YjMm5MosL0MHod8sUvPPLdg9sxeXf92E3fiLo1O7u32mM9XUvraTpl/SUQ/w\nwfWVGWiu0Ip+lqZ9OVT/bROW4rpzK1UKlK72KN20KN3sm/8+tywy1hA2ZxRKt+5PGXI9cNUFjiiK\n2YIgVHOxO50rkNVapAiCMFcUxTXNf4cCmVjz5lz50wPISK9g6SeHuf/BoZ0aStA1GNi+NYNhI4Iu\nEjcAFT8vBuBd7xh8G+p5IHpUd1T3PDw8HZh9Wwyrlp9gwEAfYge3YUVqB12DgU8+PEBjo4nHnhzV\np8UNQITgRVS0NxvXpzIw1qdLgrQ9Dh/MR7JIHXIgdnGx48FFw/ngnX18/UUiDy4a3uJfs3mjyLHE\nAu68d0i3iJu2UCoVzL19EGq1ku9XncRstjBm3MWRe+1RUd5AakopaafLKC2tp7pKj8UitZTt6maP\nh4eWsHAPhnoE4unpgIenFk8vxyvOBXS90fDFYUzp5Xh8e3enxU2DoYZ1J/7L8OBbL5rrqHV01eWG\nqySjGVNmBcbUUoypJRhTSzBlVKDyckAd7Y0m2gdNlHXZViRXTyFZJExiKQ1fH0X/cyqoFGhnxaC9\nJwFNN94b9tMEbIb0o/qFjVQ9/j3a+YNwenoiyh4Q35LeSP1nB6n//DBKZ1ucnp6AbvUJyud/hdMf\nx+Fwb0KnhyjPYtEZqHtjF7rlSdgMC8TptZuRDGYsVXosVTos1frmv63/m/KqrOsq9TgYzZS8dQzN\nYH/sxvfHdmL/llQEMr3ng/MKsFgQBGdRFGsFQQjDGlnVYiJuznGzSBCEJaIoPtYsjCRgZatyzk61\nu7Ut683luP3OwWxaf4ZPPjrIg4uGdzhMcVtzjpIb23CmNFbkUb39IxrHL+KH0jO8NW4+duqeCX8c\nOjyQlOQS1qw6QXCIW4eSYTU2mvjs40PU1jTy6BOj8PK6NpKKzZwVzZv/3cXe3TmMn9ixPEKXw2KR\n2L83h0Fx/jg5dczvyNfPmXsXDuWzJQdZs/IE8+8YzKEDeWzfmsH0mVEMib/Y2bw7USoV3Dp3ICqV\nknXfn8JsltoNQbdYJHJzqkg9VULqqRJKSupRKhWEhrkTM9AHj2YB4+HhgJu7fZedoX9rmLIrqftg\nHw73JWAT2/EXi7NsO/0pRnMjt7UzHUNbIkfp7YgprayVmCnFlF4ORuuQoSrQFU20N7ajgrGU1mNM\nLaVxSxoYmrf3c7GKnmbBo4n2RtmFiXElSbI+aIvrMBfXYi6qw1x89lNrXV9aDyYLSh9HnH4/Bu38\nQSg7GInZWVTejrh/PA/dd8eofWMXTQfycF08A5u47rkPJUmicUsatf/dgaW8AYf7h+L4yCiUDjY4\n3BFH7f92U/faTpq2Z1gdnwMvHJi4NIZjBVT/dQPmknqcn5uE9u54FB3M/yNJEuLeYwQVqmjcmUnd\nh/uoe+tXVAEu2I7vj92E/tgMDUBh0/dcD64WvdJyURRfaxYrqwRByAYSgEWiKH7WaretWDMWH2m1\nLgF4XhCEFVjnpwgFFoui+Neu1CMk1I2HHwvg848P8dF7+3n40REtIdntUVHewL49OUyaEnGRoJAs\nFkpXPofSzpH/OAYSjZLbwoZ0pWodQqGwvtG/+d9drFpxnAcfHn5J5W4wmPni00OUltSz6PGR+Pr1\nrB9Hd+Lj68TwkUFs25LO0GGBODhe+Vva6dRSqir13HVvSKeOi4j0ZN6CQaz87jgGg5nkE8WMGBXE\nhMndI7wuh0Kh4JZbB6BSKVi/LgWTycKkKdbkenq9kXSxjJRTJZxOLUXXYETroCEq2psp0yKJjPKS\n841cAZJFovrvm1D5OOL0xNjOHy9JHM5dR3zgTNy07Yf9txY5ZXO/tAoViwQqBer+HmiifNDeMgD1\nAB80gjfKNvotyWTBlG218JhSSjCeLqXhyyNIddaJXJUeWpyc1JTZHuxY3fVGzCX10GRqVVEFKm8n\nlL5OqHydsBnsj8rPGVWgK7ajglF0cyqLtlAoFDjcFY/tyGCqn9tAxb3f4fjwSBwfuzLLuTGtjNr/\nbMNwOB/bG8Jw/nwB6mC3lu0KOw0uz0/CblI4NS9stDo+PzMR+/mDLmtBkQwm6t7fR8Pnh9AM8MH9\n/Tmowzpn3VIoFEge9mjHRqO9fbB1OpCDeTTtyqTxlzR03xxFodVgOyYU2wn9sb0hDJX7b2soq9ek\nXbNTcJuOwc3b1wBrLliXBCxo+4iuERzixqNPjOKTjw7ywbv7ePixkZccstm0QUTrYMP4iee/NUsm\nA0Wf/Y66w6som/0v9laW8tXUhT0+V4+jky1zFwziy8+OcGBfHqPGtO2XYTJZWPbFEfLzqnnokREE\nBnXuTaMvcON0gWNHC/hlSxqz57Ttd9QZ9u3JoV+AC0HBnf8uhg4PpKpKz9ZNaURFe3Pr3IFX1Sys\nUCiYcUs0arWKTT+fpqy0nprqRrIyK7BYJHx8HBk+IojoGB+CQ9yualbY6xndiiSMRwtw/+x2FF0Q\ninlVyZTV53JHwkuX3fesyNEtT0Ll64Q62gdNhCeKDg6nK9RKNBFeaCK8YFYMYBVY5jM11uGs1FIq\ncopwcuvY9a+wUVuFjJ8zqmZBo/R06PLQTHejDvPA45u7qF+yn/qPD9C0JwvVPeFIYaYOf2cAlppG\n6t7fi275MVT9XHD7YE6b/j1nsR0RhOcPD1D76g5q/rmFxu3puLx0E6p2LGTG06VUP78BU1YFjr8f\ng+NDI7olt4/CXoPdBKvlxlmSMJ0upXFHJk07M6l5YSMoQB3hhU18P2ziA7CJ74fqKr3kSmYLhsP5\n6DecxlxYg/uSeVfluvnt2q5a4efvzGNPjuKTDw/y4Tt7efixkXi1cXHm5VZx/FghcxcMOs9nx6yv\no/D922k4vROfRct4tLCA0b5hTOx3dfKBxAz0ZfjIQNb/mEJ4hMdFdTebLXy37CgZaeU88NCwdrMo\n93WcnGyZNDmcLZvSGD025IrKKiurJ+10GfPvGNxlYTLlxgiCglwJDXPvleEdhULBtBkCarWSHdsz\nCApy4+ZZ0UTH+PR4YsTfIubCWure3IX93FhsR3bNwftI7k842LgR5TumQ/urvBxxerLzlqL2UCgU\nqANdrUMpNwqcSU0l5DqajVqhUeH0xFhsbwij+rkNOD2/l+K/7kXp44Q60BVVkGvz0s26DHRtsX5J\nZgv6NSepfXs3NJlw+sM4HO5L6NAQj9LRFtd/3WS15ry4mbLZS3H52xTsZ5z7biWThYalh6h7by/q\nEHc8v7sHzYCeyVCuUCiahyJ9cHp8NOayepp2Z2NIPEPTvhx0y62Byip/ZzStBI+6v2eHh8guhyRJ\nGE8Wo/85lcbNp7GUNaDyd0Z7exxcpRcuWeA04+XlyONPjuaTjw7w4bv7eOjRkedNhyBJEuvXpeLr\n57wPU4AAACAASURBVMSw4YEt6021pZz53ywMxacJ/PNPrFU5kZGaxNs3LLiqb/Q3z44hI62C5d8k\n8fgfRrc8cC0WidUrTnAquYS774/vUKK6vsy48WEc2JfLhp9SGT666/5D+/fkotVqzovK6iwKhQIh\nuve/z8k3RjBparjsWNiDSJJEzb+2otDa4PyXCV0uIzH/5//f3n3HR1mlCxz/zUx6T0gghCQkIeTQ\nCQkIiEhHBRv2XV3bXdBdr+uu14K6fVUsbNFdV1As6+pdG653qdJEQZCSUAUOJYGEEkpIJ5NMu3/M\ngDEGSJnJzCTP9/PhM+Zt53nzvp48c8573sOQlCtlQkcPCxqURMInd7F/wdf0MERjLSrDVlyO5Zvj\nmJdqHDXfTmRrjA3FlBKD44wF6/5ThFzdl6iHx2Dq9v0BJBcTMi6ToOwkKn6/nPJHF2JeuY/oX03C\nXl5L+ZOLsWw/Rvjdw4h88LIWtSq1lSkhgrAbnG/aBrCdrKY+/wj1+UewbDlM5eI9YHdgiAomaEgP\ngoYkE9AnAVNSNAFJUS1qrbTsP4V58R5qF+/GVlyOMS6MkCsVoVP6Epid1K71lCQ4DcTEhvKT/76U\neXM3MPeV9dwzfdi5l8t9s6OEg4WnuXfGJeea++tPFlI8+yrs5kq6PLyE2WWlvLlrFddnZDM4vn1f\nxhYSEsBtt2fz6t/W8fnK/UycnIXD4eA//95J3qbD3PrDbAYOavkDkb4mMMjElVP78P57W0lJM9Ga\nL5/1dVY2byxm+MjU702v4a8kufEs86Ld1H1ZQOxL17V6RFJh6RZO1xxmaOrVbo5ONMUQEoh1QDxh\njSqJsw9K24rKsBaXYysqx1Zcjr2mnuhfTyKojS/SNMaGEfOnazEv2k3FMys4ee2b2GvqMSWE0+Uf\nP2jz8d3BlBBB6BWK0Cucc+zZa+qxbD/qSnoOUz13PY7ab98ubewShikpGlOPqG8/e0SfS4BsZWec\nSc2i3Vj3nsQQEUTIxCxCfzWRoOE9vTa9hiQ4jUREBnPfAyN56/WNvD5nA3ffO5SMzC4sXriH3lnx\nKNfMzuairRT/6WqMQWHoO+by67xVVNabeWTIJGYMGO2V2NMy4hg7IZMVn+1D9elK3qbT7NhazrSb\nBpybtbojyM7pwfqvDrFqeQkZGS1/w3F+3hHq6qzfmXdKiPOxV5ipmLWKkElZhExsfbdzXtFCIoPj\n6d11hBujEy1lMBgwxYVhigtz22irpsoIvbofQUNTqJy1EmNCBJG/uNwjQ9jdwRgeRPDINIJHpgHO\n7jRbSSW2I5XYjlZgO1Jx7r8t245hO17lfOi9oSATIWN7EfHTSwm5PKNdW6jOx/sR+KDQ0EB+fN9w\n3nkrjzdf38SAQYmUnqrhjrtyMBgM1OxZzZGXb8Ael8KzOXewfOdXXJHaj98Nv4bkiNiLF+BBk67I\nQu8+wbw5G6ittTDlmr4d7g+50WhwvY/mC15/9WvuuDuXvs3sy3Y4HKxbe5A+fbsS16VzjSgQrVP1\n6jq62O1EPTWh1cewO+zkFZ3tnpJqt7MwJUYS+9L13g6jxQwBRgKSYwhIbvoBdIfFhu141bmkxxBo\nInhsL4w+Ms3PWb7x+LsPCgoO4O4fD6Vf/65s23KUnNxkknpEU7lpPsV/nEJJXBo3pE1krx3+MfFu\n3phwp9eTG3DOXXTb7UNwOBxk58Qydnz7DF1ub6GhgUye0p3M3vH8443N5G8+3Kz9DhacpuRYFZeO\nTvNsgKLDqFu1n6jHxmFqwzujCk7lUV5bwtCe17gxMiG8wxBoIiA5huDhqYRNG0jo1f18LrmBVrbg\nKKUeAYYBm4CPtdYH3RmUrwgIMPHDO3PI33yYfgMSOb3y7xx/9yE2Jvbj2czJ3Dd4Ij8dOMZjL/Jr\nrcTukfzm6cns3au9HYpHBQQYufPeoXz8wXbef28rNTX1jB7T9Evvzvpq7UG6xIfROyuhnaIU3tbW\n+ioopweh17fttQSbDy0gOrQrmfHDLr6xEMItWttW+gOcM3nPB252vYn4+Y6Y6JhMRoZeksK+9x/D\nvuzP/F9SNnsu/ynLLr2OnpG+O9y6s7yV1mQycvNtgwkPD2LBp7uorq7nyimqyYduKyrM7NxewtRr\n+8p7YTqXNtVXkT8f3aaHuO12G/nFi8lNvRqjsWM81C6EP2hVgqO1zm3w44sASqlZQNPvHvdTtjMV\n1BZsYv3CF0jRq5ifNZFhP/wjM3v293ZoogGj0cDV1/UjIjKYxQt2U1Ndx7SbBn4vyduw/hCmAGfC\nKjqPttZXpsS2vQxt38kNVJpPyugpIdpZa7uoNuP8RrQcyAMKgQv3Dfg4h81K3ZGd1B7YiLlgI7UF\nG6k/thscDuJMQWwZ/zMe/sFzhAb45lPwAsaO70V4eBAff7CNMzUWfvCjIQS6XhVvtdrZsK6InNwe\nMlVBJ+Pt+mpz0UJiw5JIj89pryKFELS+i+o54BbgSZyzgDuA19wVVHup2fEZJ9bto7ZgA+bCPBz1\nZ8BgJDh5AGG9R2G+7B4eOLiHUYMm8/SoG70drmiGYcNTCAsL5L138nlj7gbu+q9hhIYGsnNHCVVV\ndW1+A7LwS16rr2x2K1uKlzAi/UaMhs7RbSyEr2htF9XHwMcASqlooBfOiTH9Ssk7D2BKTCAkYzjx\n1/6S0F7DCUnLxRgSQa21nh/8528YE/swc9hV3g5VtED/gYn8+P7hvD1vE3NfWc9/3TecdWsOkp4R\nR/ck/5lgVLiHN+srfXw91XWnyZXuKSHaXWu7qMYDk4BlwGatdb5Syu8SnJ5PraFn/6FNPkD42w0L\nKao+zdxRl/LL/xvGXSP+yJCUK70QpWiNjF5duP+/RzJv7kZe/tMaKsrN3H6ndBF0Rt6sr/KKFhAf\nnkJa3OD2KE4I0UBr20xn4qwwVgLlSql9gN/99QiI6d5kcrP44E7e27uR/xnQj4X5j2K2VrO+8CMv\nRCjaIqlHNA+45uWKjg5hwKBEb4ckvMMr9ZXVVs+Ww0vJTb1aptIQwgta+wxOPrBMa71KKXUTEAt8\n6L6wvOdIdTmPfvUxVyR1peDgbLpGpTMwaTyf7XqV2vpKQoOki8OfdIkP5+ePjKbObO00Q+fF93il\nvtp9fC1n6iuke0oIL2ntMzgzlVLTlVKbXf3bHYLNbudnX75PlKmehNoPCQ6K4cEx/6DOeoZFO19i\n+5EVDE+/wdthihYKCQkkJERGTnVW3qqv8g4tpGtkOimx8loJIbyhWQmOUuoG4HkgDudQy1la69c9\nGZg3vLx9FVuOa26O24wBAw+Ne5fIkC5E0oWecYPJK14sCY4QPs4X6iuLzczWI8sYn3W3dE8J4SUX\nbbNXSk3AOQKhC86m3VuAfKXUtLYUrJTKUUrNUUrNUkq9qpQa0pbjtdWm4wd5eetSronOw2ar5qFx\n7xIXnnRufW7qFHYd+5JaS5UXoxRCXIin6quW+ubYl5gtVeSmytxTQnhLcx5KeBzI1VrHaa2NwGRg\nFfCxUqpVD6QopSYCm3F+s3oC5zsp8pRS2c3Y91FXYrRMKfWhq0Jrk/K6Mzy4+l3Ghm3AYCvlwbHv\nkBj13Ukqc1KmYLXXsf3IirYWJ4TwHLfXV62RV7SQxKhMkqKz2qtIIUQj30twXInDLNfQSoADWust\nZ9drrVdorScBn+BsBm6NuUCe1vqQ65hbgALggs3ISqnlgENrfb/WerJr8XLXZHqt4nA4mPnVxyTb\nPiPMUcJPLp9Hz7iB39suPiKVnnGDyC9a3NqihBBu1h711VcH3m/R9vVWM9uPrGBo6jXSPSWEF30v\nwXElDiuAya5XnN/SqAI5u93NOGfobRHXi7bSgdONVpVz8aGbE/ju/DHTXZ+tngPrX3s3UXTkTRIM\nh5k+6hVUt5Hn3TYnZSrfHPsCs6W6tcUJIdzI0/UVwOJv/sZXBz5o9vY7j62izlrD0J4yekoIb2ry\nIWOt9Uqc74xAKfUhzu6kW5RSL+B8zfkKnA/vlbaizKGuz/JGy0+7ysvWWm89z743Nfo5zvUZ3Yo4\nOFhxin9u/Q09Awq5c/gfyU6efMHtc1On8O9ts9hxZCXD0q5rTZFCCDfzcH3F0J5X8+6mmYQFRTEk\n5eJvNd98aCE9YvqSGJXZmuKEEG7SnFFU0Vrr+cB8ONcCMxHnw3vDlFKbcFYoy4F8rfXBZpbduAXn\norTWnzRadDPOCuzxlh4LYPa6p+kZsYtrBz3ByIzGudP3xUekkho3kLziRZLgCOGb3F5fXT/oMYIP\n2Xlj3c94YMxb9E287Lzbmi017Di6kin9H3TDqQgh2qI5CU6hUupZrfWTAFrrCpyVx3ylVBzObqKh\nOLuXbnX9a464i29yfkqpHJyJzQyt9RsX2G4GMKPR4iCAaMtmesVeR7pxDLt3725WucnBQ9lw5D22\n7cwnyBTayujbh9lsbvZ5+SM5P//Wt29fTxy2VfXVheqJAwcKGJlwH6fKj/H3L/6Lab1m0T286dh1\n2WosNjMxlr5+ce06+j0m5+f/2lJPNCfBmQmcVkplADPPfuNxjXhKd1Ug55qIm6HA9RnTaHlco/Xn\n5YplLjBea71NKZWutS5salut9Ws0mjlYKZUGFMbFXMojV7zUogcB45PvYd3Ct6iPPMzgntc2ez9v\n2L17t6f+iPgEOT/RhFbVVxeqJzIzM0lOTiZLvcdLn9/OwkO/5X8mfEiPmD7fK3z1mj+TGjeQkdlt\nHtzZLjr6PSbn17lddJi41rocuB9nE+8BpVSpay6XPGBWSwt0JSLlfL8FJwYo0FpXnl2glLqx8f6u\nlpvngAla622uxXNbGgfAzy97tsWjHBIie5IS25/8okWtKVII4UHurq8aCg4I44ExbxMblsRLn9/B\nyeqi76yvtVTxzdHV5KbIw8VC+IJmTc7j+nYzFOf7JGJxvkRrZhPPxDTXLCDn7HspXN+20nEmLriW\nzQE+Ukq92mBZDs5vXjk4X961Xyl12hVTi5mMrZuKKzdlKjuPfY7ZUtOq/YUQnuOB+uqc8KBofjb2\nHYIDwnhp1Q8pP3P83Lrth5djtdeRmzq1rcUIIdyg2X/htdb5OGfkbTOt9YtKKQfOBKYQyOX7z9Is\nx/kQ8eYGy1YAUa5/DR1wR1zNlZM6lU+3v8DOY58zVCbSE8LnuLO+aiw6tCsPjXuPF1fcyMur7+B/\nJnxEeHAMm4sWkt5lCPERKZ4oVgjRQq2dTbzNtNazgdkXWH9uJESDZW16MNldukamkRLTj/yiRZLg\nCNEJxUek8NC4d/njipv52xd3M+OyV9lV8iXTBs/0dmhCCJdmdVGJ78tJncqOo6uos57xdihCCC9I\nis7iwbHvcLRiL7M+uwab3SLdU0L4EElwWikndSoWm5mdRz/3dihCCC9J6zKYn14+jzP1lWQmDCM2\nrLu3QxJCuHiti8rfdYtMJzmmH3lFi+RbmxCdmOp2KY9P/jchgZHeDkUI0YC04LRBTspV7Dy6inpr\nrbdDEUJ4UUpsfxIiUr0dhhCiAUlw2iAndSr1tlp2HF3l7VCEEEII0YAkOG2QGNWLHtF92FK8xNuh\nCCGEEKIBSXDaKCd1CjuOrqTeavZ2KEIIIYRwkQSnjXJTp1JnPcM3x2Q0lRBCCOErJMFpo8SoTJKi\nFXlFi70dihBCCCFcJMFxg9zUqew4ukK6qYQQQggfIQmOG+SkTHF1U632dihCCCGEQBIct+ge3Zuk\n6Czyixd5OxQhhBBCIAmO2wxJmcL2IzKaSgghhPAFkuC4iXM0VQ27Sr70dihCCCFEpycJjpskRWeR\nGJVJfpF0UwkhhBDeJgmOG+WmTmX7kRVYbNJNJYQQQniT12YTV0rlADOAMiAGeE1rvcVb8bhDTspU\nFu18iV3H1jA4eZK3wxFCCCE6La+04CilJgKbgVla6yeA14A8pVR2M/dPV0p9qJR6xJNxtpSzm6qX\njKYSQgghvMxbXVRzgTyt9SEAV8tNAfD6hXZSSk1XSn3o2v8moIunA20Jg8FATspUth1ZgcVW5+1w\nhBBCiE6r3RMcpVQ0kA6cbrSqHMi50L5a69e11rcAz3sovDbLTZ2K2VLF7pI13g5FCCGE6LS80YIz\n1PVZ3mj5aYDmdlP5qqRoRbfIDPJlbiohhBDCa7w5iqpxC06HYDAYyEmdwrYjy6WbSgghhPASbyY4\ncV4s26NyU6ZSa6lkT8lab4cihBBCdEreGCZe4PqMabQ8rtF6t1BKzcA5HL2hIID9+/dTVVXlzuIA\ncDggJrgHq3b8LwGVSW4/fnOZzWZ2797ttfI9Tc7Pv/Xt29fbIZzjjXrCF3T0e0zOz/+1pZ5o9wRH\na12olCrn+y04MUCB1rry7AKl1I1a6/ltLO81nMPQz1FKpQGFmZmZJCcnt+Xw5zXCcj1f7vsnvbN6\nEWAK8kgZF7N7926f+iPibnJ+wl0uVE9EJyfSN7OPV+LytI5+j8n5dW7e6qKaBeQopaIAlFIZOEdW\nPXd2A6XUHOAjpdSrTexvaJco2yA3dSpnLJXsPi7dVEL4syfXfUq9zertMIQQLeSVBEdr/SLwOM4E\nZg7wATBDa/1Gg82W43zL8eazC5RSN7regzMLcAA3KaU+8LUX/gEkx/QjIaKnjKYSws/tKSvhtxsX\nejsMIUQLeW2qBq31bGD2BdbPB+ZfbJmvOvvSvzX738Vqe9Zr3VRCiLb5RfYEXtjzFYPjk7m199CL\n7yCE8AmderJNy67jHj1+buoUzlgq0cfXebQcIYTnTMvI5tbeuTy5/lO2nTrs7XCEEM3UqROc6r+v\nw2F3eOz4KbEDiI9IJU/mphLCbxkMBp4ZcT0qphvTV/2TUnO1t0MSQjSD17qofIFl70lqF3xD2HUD\nPHJ8g8FAbspU1h74F7Zhz2IyBnqkHCGE5xydcwd0i+floDA+PVrAB8UbuGXQeALD4zCGRWMKi8EY\nGkNwd4UhQLqihfAVnTrBCR6VRtWfvyRkYhbGcM9UTDmpU/ls96vsOb6O/t3HeKQMIYTnmCLicNTV\nEFB+hKtqTlB1bDsndi3BaLd9Z7ugHv1J+cVCArukeClSIURDnTrBiZgxAvv0pVTP20DUQ6M9UkZq\n7AC6hCeTX7RIEhwh/FC3O17+zvuy5uz4kqc3LeLVUdO4smsK9jPlWE4XU/L2Tzj09CiSH15ISMog\nL0YshIBO/gyOqXsU4XcNpebtTVgPN5770z3OjqbaevgzbHaLR8oQQrSf+waM5tqMwTy8cRH7HSaC\ne/QnYuCV9PzlV5giEyiaNZaaXSu9HaYQnV6nTnDA2YpjjAqh6o9feKyM3NSp1NSXo4+v91gZQoj2\nYTAYmD3qJlIj4vjxqn9SXncGgMDYJFKf+JyQ9GEU/+lqKta95+VIhejcOn2CYwwPIvLnl2Netpe6\nTcUeKaNn3CBnN1WxvPRPiI4gLDCIeRN+RFldDT/78gPsDjsAptAoUn6xgKjht3Ls9bsoXfQ8Dofn\nRmoKIc6v0yc4AKHX9SewfyKVs1bisNndfnxnN9UUVzeVvPJdiI4gPSqev15+G58f3suftn7bJWUI\nCKL7j9+iy9VPcPLjpzj+zwdxNHogWQjheZLgAAajgaiZ47Dqk9R+ssMjZeSkTqW67jR7T3ztkeML\nIdrfhJQ+PDxkAn/ZupL5B7aca60xGAwk3PgHut35d8pXv8aRv96E3dWVJYRoH5LguATlJBMypS9V\nL6/FXlXn9uOnxQ0mLqwH+UXy0j8hOpKHBo/n2vRBPPTlB/xo+VsUVJw8ty523Ax6/Gw+NbtWUPTC\nRKyVJy9wJCGEO0mC00DUw5djP1NP9Vz3Pwzs7Ka6ii2Hl0o3lfALjnobdRuKsOw/5e1QfJrRYOSV\nMT9gzrjb2Vd+ggmf/oVnNi2h2uL8ohSZfQ2pj6/EcqKAQ8+Mpv7EAS9HLETnIAlOA6buUUTcewk1\n/8zDeqjM7cc/2021T7qphI+yV9dRu2QPZY8s4Pjov3H63g84dd1bnLzuLar+vg5rQam3Q/RJBoOB\nq9MGsvqGh3lg0Fje3P0VY+bP5hNXt1VoxiX0/OVawMGhpy+jtmCjt0MWosOTBKeRiHsvwRgfTuUL\nn7v92OldhhAblkSejKYSPsR2opqaD7Zy+r6POT7qb5Q/sgDrgVLC78ily/t3EPvX6wnISqDmzY2c\nvOZNTk57i6o567EePO3t0H1OaEAQjwyZxOfTHiY7IYWfffkBNy6ZyzelRwnqlknPp9YSmJDGoWfH\ncPLfv8FuMXs7ZCE6rE79JuOmGEIDiXp4DOWPLaTuq0KCR6W779iubqqNBz/lttzfYzK699fvcDio\ns56hzlqNxVYvw1Ndth5exqnqQ4zLusftv3N/ZS0oxbxyP+ZV+7BsPwZGA0G5yUQ+PIaQ8ZkEpMR8\nZ/uQ8b1xmC2Y1xRiXrqHmnkbqP7rWgL6dCX0SkXIFYqA1FgvnY3vSY2M440Jd/LFkb38esMCrlrw\nV+5Qw3l0yCRSH19F6YJnKV30PJVff0DiXa8Q3m+Ct0MWosOR2r4JIVP6EPi/+VQ+/znxn/TEEOC+\nhq7c1Kms1G+w/+RGVLdLm73f8coC1hz4X87UlVNrrcZsafDPWo3ZUoPZWo3D8e0w97SoYfRI/zvR\noV3dFr8/sdjMfJT/B77c/y4A2w4v595LXyY2LNEtx69duoeqv6wh9Np+REwfgSHQ5JbjelLdhiIq\nn12Jdf8pCAkgeFQa0U9fRcjYDIyxYRfc1xASSOikLEInZWE/U0/dmkLMS/ZQ9ep6qv6yhsD+3Yi4\nfyQh43u309n4vjE9slh+3UO8uWsdf966gv8UbuexnMncPu13RI24jZJ//ITiF68g6tI76HrriwRE\nJXg7ZCE6DElwmmAwGIiaOZ7S297lzAdbCb89x23HTusyhNiw7uQVLWpWgmOzW1mx53UW7PgzoYGR\ndIlIJiQggtDACKJDuxEaGEFIYAQhAa5P13+fqa/gw7zf84clV3DHJc+TnTzZbefgD45XFvD6Vw9Q\nUrmf23J/T/foLN5c/zOeWXoVd434IwOTxrf62PbyWiqeXoF5yR4CB3Wn+tX11K0uIPrZqwjMjHfj\nWbiP/Uw9VX/+kjP/u4XAIT2I/ev1BI9MwxDauhnujWFBhF6hCL1CYa+pp+6LA9R+prHsPSUJTiNB\npgDuH3g503pl8+zmJTy5/lPe0xv4w4jrGDZzNRVr3uTEhzOp3raYrrc8T/TouzEYDN4OWwi/57UE\nRymVA8wAyoAY4DWt9RZP7ddSQQO7E3r9AKpe+YrQqX0xxoS65bhGg5EhyVexuWgBt+X+HqPx/N/6\nD5ft4p0Nj1Jc9g3j1L1cN+gRggMu/C27ocDqJDaUzWPOmumM6nUbNw/5NSGB4e44DZ+28eCnvLfp\nSaJCEnhs0r9JjRsAwFNXLuHt9Q/zyhf3MKnPfVw/+FFMxpb9gTevKaDiV0txmK1Ez5pC6DX9sGw7\nSvmTSzh18ztEPjSa8DuHYjD6zh+o+rzDlD+1BNuJaiIfHUv4j3IxmNzXKmkMDyJ0Sl9Cp/R12zE7\nom5hUbx0+a38SI3gVxv+ww2L5zAtI5unht1CRvY1nHj/UUremk7FundIvPPvBCfJ71OItvDKQ8ZK\nqYnAZmCW1voJ4DUgTymV7Yn9Wivy56PBYqPq7+vcetyc1ClUmk+y72TTIyksNjP/t/1Fnv3sGiy2\nOh6d9Am35Py6RckNQHhgLD+9/A1+OOxZNh78lGeWTqHgVL47TsEn1Vtr+eeGx3hz/UMMTJrAk1cu\nPJfcAESFxPPfY99m2uCZrNTzmL3iZkprDjfr2Paaesp/8xll988nIDOehH/fTdi1/TEYDARl9yD+\n4zsJu2kQVS+u5vQ973ts8taWcJgtVL7wOaV3/QtjbCgJH99JxN3D3JrciJYb2q0nC69+gOcuncbq\nI3sZM382rxXtIf7Hb5LyyBKsZUcp/HWOPIQsRBt5qwVnLpCntT4EoLXeopQqAF4Hhnlgv1YxJUQQ\nMWMEVX9di6lHNCETMglIjrn4jheREZ9LTGgi+cWLUN1GfmfdgZOb+efGxzhRdYir+j/A5LTp2Ncd\npWz5Aix7ThB8SSohk7MIGprSrGeDDAYDl2feTlbXEby1/ufMXnETV/V/kCn9H2zRA7fWw+WYl+/F\nvGwv9gozIeMzCZmcReDA7m1qTrc77Bwq3caWw0vZc/wrekT3YUjKlfRNvIxAU0izj3O0Yi/zvnqA\nk9WHuOOS5xiVcVuTcRkNRq7o9xMyE4Yxb92DPLPkKu4cMZvs5CvOe+y6zcVUPLUEe+kZon45kbBb\ns7/XQmMMCyL6qYmETOhN+VNLODXtbaIeG0foTYO80t1Qv93ZqmQ7XEHkQ5cTfs8wtz5L1lDZmRK2\nHl7CluKlpHcZwrTsmR4ppyMxGY3coYYzNW0gs/OX81zeUt7fu4nfDb+GMX/YSumCZ5wPIW/4kK63\nvUBgXAoOqwXsVhx2Kw6bFWwWHDarcxoImxWHzQIOO8Gpgwnq3set990ZSz1VFjPdwqLcdkxfY7Hb\nCLxAi7rwP+2e4CilooF0YH+jVeXAeR92ae1+bRV+51Dqdxyj6k9fUPXC5wT0jid4bC9CxvZy/nFv\nxbdho8HIkJSryCtayK05v8NoNGG21PB/219g9d5/kBLdn/8JfZnYeRZOr50HZisBWfEEZSdh/uIA\nZz7YiiEm1JlkTMoieEQqhqALX8rEqF48NukTFu18icXfvMyuY19wz8i/0DUy7bz7WA+VYV62F/Ny\njeWb4xBoIviydAJ6x1P76U5q3tqEMTGS0ElZzmQnu0ezumZsdiv7T25kS/FSth7+jPLaEsKDYumT\nOIr9JzexvvAjggPCGZA0jiHJVzIgaRwhgRFNHsvhcLC+8CP+tflXdAlPZubk/9Ajps9FY+iVMJSn\nrlzMOxseYc6aGYzLuocbsp8g0BT87bHrrFS9tIaadzYTODiJuNduJqDnhUcKBY/oScKn91A54GxS\nvwAADehJREFUayUVv12GedV+on9/BaaEpuN3N0e9lapX1lHz5kYC+nQl/qMfEdjb/Q+unqouIr94\nCVuKl1BYugWjIQDVbSR9E0e7vayOLDY4jGdGXsftahi/+noBP1r+FpNT+vLrSb8gfcQPKPnHTzjy\n0rQWHzcgLoXw/pMIHzCJ8H4TMEXEtWj/OpuVLSeLWHvsAOuOHWDLyWIsdhtpkV24LCmTUd17cWn3\nDLqEtM997QlHayr4uqSA9SUFfF1SyMHKUvrFJTIyMYMRiRkMT0wnNrhlrebCtxjaeyixUmoCsBz4\nSGt9a4Ply4AJQK7Wequ79jtPDGlA4cqVK0lOTm5W3PaqOurWFmJevZ+6LwtxVJoxxoURfHkGIeN6\nETQyDWN4ULOOBbD/5CZmr7iJhyd8gNVWz7sbHqey9hSTCq5g6MdpGOsdBPZPJGRSFiGTehOQ5qyg\nHA4Hlh0lmJdpzCv2YiuuwBARRPDYXoROyiJ4VPq5B0d3795N377f78c/cHIzb63/OVV1pdyc8+vv\ntHZYC09Tu0xj/kxj1SchOIDg0enOY4/thTHCmQA4rHbqNxc7E6AVe7GXnsHYNcIZ7+Qsgob0+E7y\nZ7HVsadkLVsOL2Xb4eXU1JcRHdqNIclXMiTlSjITLsFkDMDhcHC0Yi9bDy9lS/FSDpfvIsAYTL/u\no8lOvpJBPSYSEexMMrbtzCe/6h02HPw3I9Nv5rahv29xN57D4WCVfpNPts2iR7Tix6NeoWtkGvU7\nS6h4YjHWojIi//sywu9tedeOedU+Kn67DIfFTvSvJrb4GZXzXb/zsew6TvmTi7EWnibivpFETB/u\n1pFdJZX7zyU1xWXfEGAMom/iaIakXMXgHpMID25x66bvPKjUhNbUE23hcDj4T+F2/rBpEWV1Z7iv\n/2geGDAG07FvcNhtGIwBYArAYAr87n+bAsDo/G/sNmoPrKdm5wpqdi6jvkSDwUBI+lDCB0wmfMBk\nQjOGO/fh23vMZrezo/TIuYRm4/GDmG0WooJCGJmYwaXde9ElJJyvSwpZe3Q/B6ucL3zsE5vIZd17\nMap7L4YnZhAV1PxW1/bQ8P+ho9XlrD9eyPpjB1hfUsgh1zlkRicwIjGDzOgEtpceYf2xAo6dqcCA\ngb5xiYzols7I7hmM6JZObIhvPcPY0jrCT7W6nvBmgjNXa/2TBsubm+C0aL/zxNAL2P/ee++RmNjy\nIcMOmwPLrhLqvz5E3ddF2IrLIcBEcHYSQSNSMaVcvKK3O+z85dhPMdigkjJ6HOnGpFUjie/Rm+DL\n0gkenY6pW+SF43A4sB0opW7tQerWFmItKsMQEkDQsBSCR6VTUltGUlJSk/vWOWpZWvY2W2tWo0Jy\nySm9BOuO49hLqiDQRGCfrgQO6k6A6ooh+MKtQw6HA1vhaSw7jlG/4xhU1UFEMEEDEqnPCkZbt7C3\nNp96h5m4gG70CbuEviHDSQrqhdFw4aShzHqc3bUb2F27kcN1+zBiJC24H71Cs9lYvpRaQxVTYv+L\nweFjLvwLv4gj9fuZX/oXamxVTKi5lrAVZRi7RhH2g2xMia1vlnfU1FP7yXYsO0sIHNSdoOE9m71v\naekpunRp3qgsa0EpdZ/vw9g1krBbszElRbc25O9wOOwcPL2Nb46t5kTVQYJMwfTuNoIBiWPJSryU\nkIDWV/gTJkxIBw5rrX1y7pK21hOtVWut5+096/mX3kRcSBjT+48msZVdQ4aKEgIP5hFwcBOBh/Ix\n1NXgCArD0jMHa8+hfGO2UeIws7/iBLVWK4FGE5nRCWTFdCUrphspkXEYm+jqOm2uYV/5CXTZcfZW\nHKe8rhYjBlKiYlEx3ciIiifQB945dbDkKKeM9ewrP8Epcw0AiWFR9I7pSmZ0Ar2juxEV/N2kzAGU\nmqvYV3aCfeUn2VtxgnLXRKlJ4dH0julGZnQCYQHN/0LrKadKTxHfzDrCV0R3SSE9I7fZ27elnujw\nLThKqRk4R101FA5cvB9DCOFp6Vrrg94OQuoJIXxaq+oJb6TYBa7Pxs0ccY3Wu2U/rfVrOEdbnaOU\nCga2AlcDtovE68/+A1zr7SA8SM7Pv/0HaN4wNg/rxPVEZ7jH5Pz8W6vriXZPcLTWhUqpcr5NTM6K\nAQq01pVnFyilbtRaz2/pfs2IoU4pVaO17tDT+iql6n3h27GnyPn5N9f5+WT3FHSOeqKT3GMHvR2H\np3T084O21RPeeiHGLCBHKRUFoJTKwDlC6rmzGyil5gAfKaVebcl+QgghhBBeeQpMa/2iUsqBM4Ep\nBHKBGVrrNxpsthy4GeeL/VqynxBCCCE6Oa895q61ng3MvsD6+cD8lu4nhBBCCNGZ39n+2sU38Xsd\n/Rzl/PybP5yfP8TYFnJ+/q2jnx+04RzbfZi4EEIIIYSndeYWHCGEEEJ0UJLgCCGEEKLDkQRHCCGE\nEB2OJDhCCCGE6HAkwRFCCCFEh+P96V7bmVIqB+ekemU4p3l4TWu9xbtRuY9SKlprXdHg5yFAWUd9\nnbdcT//na9fQ1+Jxt85wTzUk17NjaM117FTDxJVSE4FlOGcmPeS6EfKAnKZmIvc3DWZcB8gHMoBS\nrXVv70XVNkqpdOB5YKPrJY8N1/n99bzI+fn99VRKPQr0whl7OTBXa72ywXqfuoa+Fo+7dYR7qjGp\nI/z/enqqnuhsXVRzgTyt9SEAV/ZXALzu1ajcy+H6lw7M8bcb/Syl1HSl1Ic4r9lNQJcmNvPb69nM\n8wM/vp5KqeWAQ2t9v9Z6smvxcqXUIw0287Vr6GvxeILf3lMNSR1xjl9fT0/WE52mi0opFY3zBtjf\naFU5kNP+EXnM442zfH+ktX4deN31DWVi4/X+fj0vdn4N+PP1nIDzWpyNfzrOivoJYLavXUNfi8eD\n/PmeOkfqiHP8/Xp6rJ7oNAkOMNT1Wd5o+WkApVS2vzRZXkSmUurs7OoxOJv6Okx/cwNyPX3fTY1+\njnN9Rrs+fe0a+lo8nuLP91RLyPX0Dx6rJzpbFxW4fikd1Glgv9Z6ptZ6Js4+yjyl1Hgvx+VJcj19\nlNb6E631Jw0W3YyzKf3xRpv62jX0tXjcya/vqVaS6+nDPFlPdKYWnLPiLr6Jf3Jl7Q0z9xWuz7mA\nX/XLtoBcTz/gGgHxODBDa/1Go9W+dg19LR636Uj3VAvI9fQT7q4nOlMLToHrM6bR8rhG6/2WUmq5\nUurVBovOZrwZ3ojHw+R6+gmlVAbOCne81voN16gQ8L1r6GvxuF1HuaeaSa6nH/FEPdFpEhytdSHO\nPrzGWWAMUKC1rmz/qNxuAhDb4OezN/kBL8TiUXI9/YPrG9lzwASt9TbX4rnge9fQ1+LxEL+/p5pL\nrqf/8FQ90WkSHJdZQI5SKgrOZYzpOH+xHcFHwGsNfp5E032Z/sRwgXUd4Xpe6Pz8+nq6Kq2VOEc6\n5Cul9iulTvPdCtnXrqGvxeNufn1PnYfUEd/yu+vpyXqiU73oD8A1tn4SUAjk4nxvQOO+Pr+llJqD\n88Yw4LwBHtNaf+7dqFpOKXUjcCvOc8jB2QyZD2xqOCTSX69nC87Pb6+nq5KKbmLVR1rr2xps51PX\n0NficTd/vqcakjri3HZ+fT09WU90ugRHCCGEEB1fZ+uiEkIIIUQnIAmOEEIIITocSXCEEEII0eFI\ngiOEEEKIDkcSHCGEEEJ0OJLgCCGEEKLDkQRHuIVS6jGllN3bcQghfJPUEaK9SYIj3MXh+udTlFKb\nlVIfeDsOIYTUEaJ9dcbZxEXnModvJ6ATQojGpI7ooKQFR3iMUupG12u4vVaW1nqe1vqT9ohBCNEy\nUkcIT5IER3iSgfZrkm7PsoQQ7iF1hPAY6aISHqGUWgZMBByuBwsdQC+t9UHX+rnAzTibhudqrV9s\nsF8+sAl4AnhWa/2Ja+K5J3BOOncAmKm1nn+xslzrDmitf9IgtueBG3FOUPdho3XLcE5qVw7McMX3\n+NmyhBDuIXWE8DRpwREeobWeDNwHlGutjVprU4OK6yOcldA44DFgplJqfIPdbwKeA54BVriWxbq2\njQEeBz5SSmVfrKzGXGWPx1l55QK9lFKbG202HdjnijEfeK21vwchRNOkjhCeJi04wpO+19+tlMrB\nWXFkuCqYbUqpS3BWPqtcm6UDMVrrqrP7aa3nNTjMJ0qpApzfyLaer6zzlH1Do2NPVkqdVkr9uEEZ\nBVrrN1z7zAVuVEpFaa0rm3XWQojmkjpCeIwkOKK95bo+Dyil4Nt+8bwG26xoWHEBKKWicTYH3wpk\nANFAr1aUXdD42MBm17qzlVd+g3VnK8U4QCovITxP6gjhFpLgCG84oLXufYH1BU0sy8dZydyotT7U\nRJNxc8TgrIQuRoaMCuFdUkeINpNncER7WwFkKKXSmruDUmoIkAZM11ofamPZMQ3LVkrFAENxVoxC\nCO+TOkK4hbTgCE8qAGKVUhNwfjM6oLXeqpSaDyxXSt3v2mYSMKThSIUmjmMAXnCNbpiE8+G+TRcr\nq+FBtNZblFIrGpRdBjwPnDrbn34ehpadthCimaSOEB4jLTjCnb7zjgmt9Rac/eYf4uwbL3ctvwX4\nGJgL7Mf5QOHc8x1Ua12Bc1TEdJzfotL5bn/8ectq4lhXuMr+EFgOlOL8dtbkOVxgmRCi5aSOEO3G\n4HDIdRFCCCFExyItOEIIIYTocCTBEUIIIUSHIwmOEEIIITocSXCEEEII0eFIgiOEEEKIDkcSHCGE\nEEJ0OJLgCCGEEKLDkQRHCCGEEB2OJDhCCCGE6HD+H2eLoaWG+8H9AAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<matplotlib.figure.Figure at 0x1174c2c50>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "\n",
    "fig, axs = plt.subplots(1, 2, sharey=True)\n",
    "\n",
    "for i in range(phi_1.shape[0]):\n",
    "    axs[0].plot(phi_1[i,:20])\n",
    "    axs[0].set_title('Topic 1')\n",
    "    \n",
    "for i in range(phi_2.shape[0]):\n",
    "    axs[1].plot(phi_2[i,:20])\n",
    "    axs[1].set_title('Topic 2')\n",
    "    \n",
    "fig.set_size_inches((8, 3))\n",
    "sns.despine()\n",
    "\n",
    "for ax in axs:\n",
    "    ax.set_ylabel(r'$\\phi_w$')\n",
    "    ax.set_xlabel('Iteration')\n",
    "    ax.set_yticks(np.arange(0, 0.5, 0.1))\n",
    "    \n",
    "fig.tight_layout()\n",
    "# fig.savefig('phi_over_time.png', dpi=300)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[ 0.12359551,  0.1686747 ],\n",
       "       [ 0.2247191 ,  0.08433735],\n",
       "       [ 0.3258427 ,  0.3373494 ],\n",
       "       [ 0.12359551,  0.20481928],\n",
       "       [ 0.20224719,  0.20481928]])"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "phi_orig  = WT_orig/(WT_orig.sum(axis=0))\n",
    "phi_orig"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAA1gAAADQCAYAAAAalMCAAAAABHNCSVQICAgIfAhkiAAAAAlwSFlz\nAAALEgAACxIB0t1+/AAAIABJREFUeJzs3Xl8FFW+P/xP8/N5JuklUeYZJMS5AwQ47LLjigsRRQkw\niCyCgmAAnSuyiIiyhE32AOIoIQgu7HuAgWEHnavsoix6CAnML0l3krkESC/J3GX6+aMqne5Od6fT\n6aTTyef9evkiXd9Tp6qt6lPn2+dUtcZut4OIiIiIiIgqr16od4CIiIiIiKi2YIJFREREREQUJEyw\niIiIiIiIgoQJFhERERERUZAwwaKQEkJ0FEKsDvV+EFHtwXaFiCqK7QYFExMsCrV4ADdCvRNEVKuw\nXSGiimK7QUHDBItCrSuAo6HeCSKqVdiuEFFFsd2goGGCRaHWU0p5KdQ7QUS1CtsVIqoothsUNEyw\nKGSEEE0BZIZ6P4io9mC7QkQVxXaDgk1jt9tDvQ9UhwghBgIYA6CpusgOpVHTAJgqpfwxVPtGROGJ\n7QoRVRTbDapKHMGiaiGEiBZCHAGQAmCBlLIZgIsAxkgpnwewHcAFIcSAUO4nEYUPtitEVFFsN6g6\nMMGi6nIcwLMAOkkpT6jL4kv+llKmqstSPa1MROQB2xUiqii2G1Tl7gv1DlDtJ4R4H0BHAKullH9X\nlzUBkOFW9C6A+z2sHw1gGoAmUIbvH4AypL9ISnmsgvtyA8q3VMerch0/6kyE8u3ZEfUbMyKqgCC1\nK4ugTAuqD6AAwD0AZ6WUu5zKDHLqcAVjv4NeJxH5pzLthlpuEYCB6qLt6r8aKI94t0spf1uJfesJ\nYAeAf1WmHqoZmGBRdYiH0onZ4bbM8ThUtdNxP4A7zisKITqp5VZLKQc7LX8ZwBEhRHwFE5/VASRK\ngazjk5QyVQiRAuBwMOslqkMq065EA7gJ4OWSb63VZXdQej8GACyG0pkKZjJUFXUSkX8CbjeklDeF\nEAugfH4Pu/VJogGcr8yOSSmPCSFuV7Yeqhk4RZCqQxf1X+dG4zkAR5xej1X/dSwTQtyvrnNYSvmh\nc4VSyp1u6/lFSrm0IuUDXac8QoiSRr5CI3BE5BBQu+K0PNppehCklPegjCjfcirXE8H/XZyqqJOI\n/FOZdqOkrCOmjmqVtB8XK7Njap+nqZftUpjhCBZVh/NQOhXOOpaMCqmNyjQoU3TGOJVJhZKETHWv\nsKRRgzqEL4RYDaXhTAEQpy4/UpKICSEWQmm4MqWUHzjVMwbKt1cZUKYeDpJS1ve2jtN2FkCZVnQ/\nlAZ3u/uUHw91x6s300JdB/zNDaKABdquAEq7olGn/x6F2laUTNdVR8jHQvn8ZwghPpdSvlWysq/P\ntre2SF3Va51EVC0q024ApSNgJV+Obkdp0jZVrSPQfkJn8IvXWoMjWFQdShKkRYCjAbun/h0P5b6q\nf0D5kb9Cp/VehpLc/N1DnZ3Vfy8KId4EsFp9PUZNhuKhNnpqZ+kslAYzsaQCdS72AgCjpZTT1MV2\nb+uoy0q2swbAVinlEnX/33feOSHEIm91q/gtNlHlBNquQP3cHoFyX2cigO1CiHSn+E4oCZIdwEC3\n5MrrZ1u9t9JjW+SrTiKqNgG3G6qSZGqa+gXN7ZKAlPJWJfsJmQDuuo2iU5higkVVTv0tiTgA9YUQ\n56AkFk3UDs0CAPOllC2klD+VrCOE6Kj+6e2H/8ZC6ahsBbBNHQnqBGCLGu/k1Pk5ot60PghKB6dk\nvvRCKI2fWS3XBaVJT5l11GUl2/nYqfGNh9PUALXuKW51u8zxVuvg/VdEAQqkXXFb/3kp5f9B6fSg\npkKIZ52K9ILyBU/JZ9ifz/bWctqiMnUSUfWpTLuh9ktKZscMhnIvVslUwWh1Zk0w+wkUxjhFkKqF\n+o3MYMAxfP5xyZO6vLir/lsmwVIffNETysMnLqnLXIbtnb95klIWqj8oGA1gjdqwlXwLdcGpaken\nyNM6Usp77ttRf/29KYApJWVQOoWgpOEtmVd9WN1215I6nNYhogoKoF0pmfq7uuRbYinlcSHETQA3\n4Nre9IT6JYi/n21PbYTbt+Ce6iSiahRIu6Fy+fxLKS8JIUrajEUAFqp9h0D6CdFqmQVsG2oHjmBR\nKJT7LY2U8iaUb3sGOS9XG6ptUB588bZTqLx7msao9T0A4AMoU//sUBMsNZmyu+2X+zqetvMylEez\n7oY65QClyWHJr8APUuu+pJaJV5ffhDLXm4gqz99vfwei9DNYYiqU+yNuAS6dnYtOo91A+Z9twEtb\n5KNOIgqdiowa9VL/ddwjpSZUYwA84DS1L5B+wmAobclxpzIUxjiCRaFg9zK32d2zABapw/jnAfwW\nSgM0RW2onEWjdCqfJ9sAvALlIRbTAEAIsVit/6Iac+8UlVlH3Y5z43cRSodpAdQOk/qo1TVO+15S\n7n0oc7M1UL7JXggPD/AgooD4265kALhfCLENyv0T9QGcc35aqDoStR1KRykO6ufUj8824KUt8lYn\nEYVUue2GOjVwGpQ+CaDcfwUo1/JOUO7l7OS0SjD6CRTmNHa7vfxSREGiNlRjatoN3kKI8wBuS/7o\nL1HYqantChHVXGw3qCoxwaI6SQhxGMrN5uPUaYfpUJ7s5T4yRkRERETkNyZYVCcJIT6HMjXoPJQH\nXhyWUn4R2r0iIiIionDHBIuIiIiIiChI6uxDLnb8ZGJmWYf1aRMT6l2gEIq4Dxp/yt36z2K2E3VY\n0X/9b6h3gUKoVSOdX+1E2uVcthN12POtGoZ6FyiEvPUn+Jh2IiIiIiKiIGGCRUREREREFCRMsIiI\niIiIiIKECRYREREREVGQMMEiIiIiIiIKEiZYREREREREQcIEi4iIiIiIKEiYYBEREREREQUJE6ww\nV2yzYP289zBvVF+kpSb7LJuTeV0p+0YC1s+fgmKbtdIxCh2z2YyxiaPQ47HumDdnVsBlA41R+LBa\nzJg2YSwG9u6BT5bM82ud7Ru/hNVqcVmWLn/ByEF9KlQPhZbVYsasKW/jtX7PYPXyj/1aZ/eWr2Bz\nO/YA8NOFM5g8dhhe6/cMvkldValtUM1TZLUgdc5kJI1MwK41y3yWzc68jtQ5kzFrZB+snfuex37B\nybTNHpen/3weK98fg6SRCTi4cU3Q9p8Cx/5E8DHBCnO7Vy9F84e7Yvq6vbDb7Ti0McVjuWKbBVuW\nJ+GF4eMwff0+NGrcDLtXL6lUjEJrzqzpeOzxJ/Dt92dgt9uxInlpQGUDjVH4WL5oDjp3fww7Dn4L\nu92OLz5f4bP8dyeOeCyzctEcLPpkDb7acQCmnCysXDy3TJkDaTvwwhMdyiRnFBp/XjoPHbs+im/S\nTsBut+PrNZ/4LP/9qaMey2Rc/wWfJ8/H1NlL8E3aCfRKeNkRWzx7Kp54uhe+STuBwnv3sHvLV0F/\nH1T1dq5eghYduiHpy32w24EDGzz3J4qsFmxMTsJLr7+F2V/uR6MmzbHj88UuZX7+4SQOelg/O/M6\ndq1JxutT5iDpy33o/lxClbwXqhj2J4Iv4ARLCJEohDgczJ2hiim2WZBx5SKeSBgMAHhh+FicO7rf\nY9kIrR6jZixDTONmAIBm7bvAdCu9UjEKHbPZjDOnT2PEyFEAgAmTpmDn9m0VLltYWBhQjMKH1WLG\npfNnMHDoCADAm29PwIG0nV7Lz5sxBQfSdkCj0bgs/+7EUXTq+ggebNgIOp0e774/Awf3utZjtZiR\nLn8psy6FhtVixuUfz6L/oNcAAK+PGY/D+3d5Lb84aSoO7d/l8fh9tmweRo6bgAYNGwEAHlT/zTPl\nIPP6L3jupf4AgIHD3sChfd7PL6qZiqwW3Lh8EU/1VfoTLw4fizNH93ksG6nTI3HmMjRS+wXN23dB\nzs3SfsGGZbNw5sg+wMN5tHP1Urz02jg88LuGAID6DWKC/VaogtifqBqVGcHSALAHa0eo4nIyJGLj\nhON1hFaPYpvV6xS+B5wasss/nERcu86VjlFoXLt6Ba3btHW8NhgMsFjMsFjKjhr4KvvLtasBxSh8\nXP/1Glq0bO14rdMbYLNavI4wTZ+7BAtWpMBud23en3wmHoNfH+143bDRQwDgUs/az1agT/9Xgrn7\nVAk35DXEtWjleF1y7D1N/wOA95MWYfaSz8oc+zxTDm7ekHjkyWfLrJNx/VeXbTRt3hL5ucYgvQOq\nLtkZEg859Scidb77E86J0c8/nETz9qX9guGTZyNx5jLA7TwqyDPBeCsdbbv3CPLeU2WwP1E17iuv\ngBBiNYB4APUBZABIBPAhgIEA7EKIAgC3pZTN1fLnASwA0Est0wRKMpYKoCeAAgCLpJRr1fKJAKaq\n9d8GME5Kecyprq0AngPQRd3+GACD1X/tAD6QUqZW9n9EOCrIMyFSq3dZFqHVoSDfiEaNm3tcJ+Py\nBZw9sg+mW+l4e+GaoMSo+mVnZcEQZXBZptcbkJ2VhZatWpVb1mCIQnZWVoVj3rZBNZfJmA2d3vU4\nanV65OZkI65FywrVpdOVtjclI1Uly0w52cgz5SCuRcsyHXQKjTxTjudjb8pB02bCy1pl5Rqz8WBM\nLHZv+QqH9u2ERqPBlKTFjjos5kKX8na7HXm5RscoF9V8BXlGROg89CfyjGjUxHN/Iv3nCzhzZC9y\nbqbj3cXld8Nu5xlRv0EMTqZtVka4ALw2ebbX+ql6sD9RNXyOYAkhXgbQWUrZTEpZH8ArADKllIMA\njAVwVEpZvyS5cpIK4F8AGkspCwEcA7BFSvlbKInSOCFEY7XsbQAd1foXAdjuVtcHAF5W43cAXABw\nRn29EMDqQN54bRXpdjF1V5BngkajQYROD5ulMCgxqhmio6P9LhsVFRVQrCLboJrLEFX547h1wzqM\nfnuC4/UnS+Zi9NsTK10vVS29wfvn25s8Uw5yjdnQG6KxeuNe9OozAH9eMgcA0LBRLHKN2Y6yGdeV\nxNtqMQdtnyk0tHrf50pBnhHQaBCp08NmLr9fUJBnREGeEVp9FKZ+ugndn0vA9s95T3dNxP5E5ZU3\ngnUXQFM10ToqpbzlZ73npJRvAYAQoieATgAWCSFK7oK0QxkVWyuldEwIl1KuFUKsEUJ0kFJeUhdv\nk1KWtNRHoCR8u9XXOwAsFEJEqYlcGUKIMVBGu1zM33bSz7dSc0XqDSiyuQ6vFpVzUesa3wdd4/vg\nyulTWD93Miav2lTpGFW/6OhomAtdj/W9e/cqXDbQWG3jrZ049B8/hWBvgstgiC7T2TUXVu44fnfi\nCGwWs+O+ru9OHIFGo0Fcc/9HRajq6T0ce/fRJn/r0RuiHPdZ/XHICHy95hPYrBY0bd4SGo0GR/6y\nG8+99EfHPV4NY2Ir/wZqGG/txOIdp0KwN8GlNUSh2G3qaHlfpnZ/LgHdn0vA5dOnkDp3MqZ+6rtf\noDVEIVJnQLeeLwEAnu43FAc3pKDYZkWEVle5N0ABY3+iavhMsKSUx4QQC6CMLDURQhwF8Iq3ZMbJ\nEae/mwI4IqV83lNBIUQ0gGlQEi6g7H1dGW6vM53+LihnPyClXAOgzJy2HT+Zwn4OS6ROjyK3BrDY\nZikzbdCTto88hS3Lk3An3+Ryj1VlYlR9DFFRKLx312WZ2VxYZgi+vLKBxmobb+3Erf8sDvt2Qm8w\nwFzo2k5YLWboDIEdx3T5C7ZtWI9VX5R2pi6eO43rv17DwN49HNMDRwx8EaPfmoDefQcEvvNUKTq9\nvkxCZbWYy0wbLE/DRrF40C1h0ukNjqmGs5etxuJZU3Bo3068PmY8jvxlN7S68q9D4cZbO5F2OTfs\n24kIbdnZKcVWS5lpg560e+QpbFg2CwX5Jp8PrajfIAb1H3SNR+j0PqchUtVjf6JqlHsPlpRyKYCl\nQogoAMehfHtT3rMVnf8vZkKZFliGmlzdBDBaSvmBuuxffuw3AYiNEyjIMzleK3OoDR4TH/eGr8hq\nhnJrXOAxCp3WbdoiO7t0Wk52VhaioqIRG/tQhcpGRUUHFKPw0aJla5icpnCZcrKhN0SVO8Lg6Uly\nFnMhPlk8F4s+cb3f4t33Z+Dd92c4Xvd+siO+3nEQWh2/lQ6lZqI18kw5jtfKNL+ocu+Ncj/2D8bE\nutQDADarxXEONW0msHrjXgDKY9579WFSHW4ecutP3M4zIlJn8JgwFeSZXBKlIqvZ4xMD3ZfVf7CR\nyzYAoNhmRf0Hea9eKLE/UTXKuwerpzrFD+qolfOIUQGU0SkIITp6q0N9YEWmEGKrU70vCyE6QHmw\nRTSAH9XlAwN4D3W2tx+h1SM2TuDcMeXR7N+mbUa3+NLflCjIN6FYnUJ4J8+IzclJKMhXGrdTuzeh\nWfvOeKBBTIVjcWqMQsdgMKB1m7bYtUO5ZXH9ulQMHDTYEc/OzoLZbC63bKAxCh86vQEtWrbGwb3K\n1K1tG9fjxX6lTW2uMdvj/TKeHlQxf8YUfDRvSbmJk91uh50PmQ05nd6AuBatcOQvyqz63Vu+ckl+\n8kw5fh17nd6Ax59+zvH7Vrs2f4lHe/R0jFJlpv8KQDmXvkldhT8OHVkVb4eqUKROj4fiBM6oP/Vy\ncs9ml9+oKsgzoUidQng7z6iMWKnJ0oldG9G8XeeyyZjbeRSp06P9Y0/jZNpmdRub0O6Rpzg9MMTY\nn6ga/jymfaoQokAIcRvKQyZKhsePAoC6fKE6wgV4fnR7TwAap3oGQXlYxk0AO6EkYOkAOrut788V\nuk5fxYdOTMKVH05i3qi+0NSrh16vJjpihzakOH4XK65dZ7R//FlsTp6FeaP6wvT3GxgyMSmg2FA1\nRqG1dPlKHDp0ED0e6456mnoYP2GSI7YyeSl27djmV9lAYxQ+Ppq3FN8eP4SBvXugXr16GDVuvCO2\n9vOVOLC39LeRVi6ei5dfeBIajQYjBr6IDyeOA6D8DtalC2fxxqA+6P1kR7zwRAf0frIjct1GNgDP\no18UGu8nLcbfTh7Ba/2egUZTD68lvuOIfZXyiSP5AoDPk+djeN+nodFoMPbVBCRNedsRey3xHVy6\ncAav9XsGP188iz+9VzpieWjfTgzv+zSWzvkA7yct4dMDw9TwybPx8/cnkDQyAfXqadB7WOntZgc2\nrMZZtT/RvH1nPPx4T3yzbBaSRibAeOsGhk+e7Si7M2UZZo3sA2g0WPj2EKyd+54j1nvYWKT/dB5J\nIxNw4/JFDBw3pfreIHnF/kTwaerq43Rrwz1YFLg+bTgCV5dF3OffyHdtuAeLAlf0X/8b6l2gEGrV\nSOdXO1Eb7sGiwD3fqmGod4FCyFt/ojI/NExEREREREROmGAREREREREFCRMsIiIiIiKiIGGCRURE\nREREFCRMsIiIiIiIiIKECRYREREREVGQMMEiIiIiIiIKEiZYREREREREQcIEi4iIiIiIKEiYYBER\nEREREQXJfaHeASKimuo/zf8V6l2gEHqofmSod4HCwD//91+h3gUiqmE4gkVERERERBQkTLCIiIiI\niIiChAkWERERERFRkDDBIiIiIiIiChImWEREREREREHCBIuIiIiIiChImGCFuWKbBevnvYd5o/oi\nLTXZZ9mczOtK2TcSsH7+FBTbrJWOUeiYzWaMTRyFHo91x7w5swIuG2iMwofNasGCD/8dY1+Jx7pV\nC32WvZn+Kya98UePZX3FqGayWMyY/E4iEuIfx7KFcwIua8rJxuR3EtEn/jG8984YWC2WqtxtCoFi\nmwVfzp+Cj0f3w961y32WNWZeV8qO6ouvKtAvMGZex/Lxw/zaBlUf9ieCr9oTLCHEDSHEgurebm21\ne/VSNH+4K6av2wu73Y5DG1M8liu2WbBleRJeGD4O09fvQ6PGzbB79ZJKxSi05syajscefwLffn8G\ndrsdK5KXBlQ20BiFj7Ur5qN950eQsv0o7HY7tqxb5bXsF598jGkLP8PyL/cgz5SNLz5Z4Fds4hv9\nMfzF7hjeuxuGv9gdn3w8rUrfE/lnyfwkdHvkcew7+h+A3Y6UT713an2VnfxOIt56ZzL2H/0eT/Xs\nhZnTJpZZf+/u7Xi6ezsmX2FqT8pSNG/fFR9+kQbY7Ti8aY3HcsU2C7aumI3nh43Fh+v2IqZJc+xJ\nKdsvOHd0H2YOedYl+UpLXYY3ZizDpFWbUJBnxN5yvhim6sH+RPCFYgRrDADPWQBVSLHNgowrF/FE\nwmAAwAvDx+Lc0f0ey0Zo9Rg1YxliGjcDADRr3wWmW+mVilHomM1mnDl9GiNGjgIATJg0BTu3b6tw\n2cLCwoBiFD5sVguuXjqHl14eDgAYOvodHD+wx2PZs387jrYdu+F3D8ZAq9Nj9PhpOPHXPd5jB3eX\nbsdiQeqO49hw8Cw2HDiD8R/ye7RQs1jMuHjuNAYPGwkAGPvOJOzbs73CZU052dAbotCsRUsAQEL/\ngbhw9nSZ9dN/vQaNRlM1b4aqVLHNgswrP+LxhEEAgF7DxuC8j/7EyOml/YK4dp1hunWjTH2mm+kA\nSs+Hq2dOIa5dF9z/u4aI0OrQL3ESzh/zvA2qPuxPVI1qT7CklMellLeqe7u1UU6GRGyccLyO0OpR\nbLN6Hap/oEGM4+/LP5xEXLvOlY5RaFy7egWt27R1vDYYDLBYzLB4+ObYV9lfrl0NKEbhI/P6NTRp\n3srxWqvTw2azwGYtexy7PfEs+g4e6XjdoGEsYLfDZrV4jgEu9djt9uC/AQqYvHYVolUbx2u93gCr\nxeJxhKm8sqacbJfyjR76vcvrlFXJ6Pvy4GDuPlWjnAyJ2KYtHK/L7080dPx99fSpMv2CwxvXoOtz\nfV2Wten+FHr0f9WpDqVvwdsOQov9iarBe7DCWEGeCZFavcuyCK0OBflGr+tkXL6AzclJyLxyEc8P\nGxuUGFW/7KwsGKIMLsv0egOys7L8KmswRCE7K6vCMW/boJorPzcHWr1rO6HV6pGfm+OxvFZXWvZm\n+q+ARuNY5itmt9uxcv4HGDOwJ6cH1hBGYzb0BtfPsE6vh9GYXaGyMbEPQbRqg1PHjwAA9u3Zgfc+\nKL2HwpiTBZMxB81btGSSHabu5JsQoSvbn7iTb/K6TsblC9iyPAkZVy6i16tjHMsL8oy4k29SR7hc\nz4cIrc7xtzHzOgCNyzKqfuxPVI0qTbCEEOeFEC8LIVKEELeFEFHqsjfV+GohxDa3dd4XQhxS/44W\nQmxT100vWc9b3VX5XsJFpN7gM16QZ4JGo0GETg+bpTAoMaoZoqOj/S4bFeX94+IrVpFtUM2lN/jX\nXO7b9hWGjn7Hr5hGo0HT5q2wZscx6PRRLvdnUc0RFVWRdqK07NJVa5DyaTKeeaQ9Nn+zDjGNYh2x\nZQvnYNw7k4K6nxR65fUn7uQr/YJIrR5FTv2CvWuXo5cfX8R+m7aJX9jWUOxPVF51jGClAvgXgMZS\nSveeeQqAl92WjQGwWv37GIAtUsrfAugCYJwQorFb3f/rpe5aL1JvQJHNdXi1yGL2uU7X+D4YMnEW\nevR7FevnTg5KjKpfdHQ0zIWux/revXsVLhtojMKH3hANm9s0DIu5/ObyzHfHYLNaHPdulRebt+pr\nDH7jTwCAhEGvu9yfRaERFRUNi9n1M1xY6PkzXF7ZMa8Pwrh3JuPE6Z+R0H8gEkco9+qcPHYYGmgc\n92dReIrUG1BsrVh/okvPPhg8YRae7D8UX857DwBw5fQpaADH/VneXDl9Cv+0WR33fFHosD9RNaoj\nwTonpXxLSlnmkyql/BFAphBiAAAIIToBeEBKuVsIEQ+gE4BFQogbAC4AiAYQ71b3257qLiGEGKOO\ndrn8F8w3GCqROtdvjQDlxlL3aYOetH3kKdzJN3kc/g80RtXHEBWFwnt3XZaZzYVlhuDLKxtorLap\nze2EVqeH1ex6IbNZzdDpvB/Hm+m/Yv+2r/DBx2WfNugt9ruGjRx/6w3RgEbj8T4vqj56vaFMQmUx\nm6H3MDLhq+yp40cAjQY9nlEuv0NfGwWrxYL067/iwtkfIH+5ioT4x9En/jEAwJD+z2P/nh1V9K5C\npza3ExFafZmEqthmQYQf/Yk23Z/Cnfxc3MnPReblC8jJvI6PR/fDx6OUe7CS33kV54/9xVHemHkd\nf0vbjBEf8YnENQH7E1XjvmrYxpFy4msAjAWwS/23ZMpgEwBHpJTPV6JuSCnXqNtwseMnU9hPFI+N\nEyjIK010CvKMiNAZXB5K4Yjlm1DfaXmR1YySp/sEGqPQad2mLbKzS++jyM7KQlRUNGJjH6pQ2aio\n6IBitY23duL8zcKwbyeatmiN/NzS+zLzTdnQ6aNcEiJnVosZ6z75GB8u+rxCMWd56j0+Wl35nTOq\nOqJ1G5eHUxhzsmAwRLlM7/On7PVfr5Upr9ProdcbMHnaLEyeVno/1jOPtMfWtMPQ6mrffTXe2olt\nl4xh307ExgkU5HvqTzQsU/ZOvsmln1Hk9EVK38RJ6JtYOl105pCemPzpZvwmUusouzc1GW/M5OPZ\nawr2J6pGdYxg3S0nvgZAvBAiGsArKJ0emAllWmBl6q7VIrR6xMYJnFMfc/pt2mZ0i09wxAvyTShW\npxDeyTNic3KSowE9tXsTmrXvjAcaxFQ4FqfGKHQMBgNat2mLXTuUxyivX5eKgYNKn+CVnZ0Fszrd\nx1fZQGMUPrQ6PZo0b4UTB5XHre/b/g2effGPjnh+bo7LSNMnH0/D+I8WItLDjefeYld+PIsFH/67\no54t6z9FwiuvV8XboQrQ6w0Qrdo4RpM2f70OCQNeccRNOdmwqKMWvsp27vYITDnZuHjuDADl964a\nxf7eY6Jmt9v5oIswFKHVI7ZpC8dI09/2bkHX+D6O+B2n/kRBnhFblic5ZrJ8u2cj4tp18piMAa7n\nw9YVszF4YpIj4aLQY3+iaoT8KYJSynsAjgJYBOC2lPIndfkxKNMHt5aUVR9q0SE0e1ozDZ2YhCs/\nnMS8UX2hqVcPvV5NdMQObUhx/C5WXLvOaP/4s9icPAvzRvWF6e83MGRiUkCxoWqMQmvp8pU4dOgg\nejzWHfU09TB+Qum3hiuTl2LXjm1+lQ00RuFj/EcLcPq7oxj7Sjzq1dM47pUCgC1ffOq4X+rs347j\n6qVzmDgPOtxXAAAgAElEQVTqjy4/GvyPXKPPWNuO3dCuY3dMGNEPY1+JR9PmrVy2QaEze0EyThw7\nhIT4x6GpVw9j3p7giK3+dLnLVD5vZfV6A5I/+wKrVy1DQvzj+Pb4ESz/8xcet8ffwQpfgycm4crp\nk/h4dD9oNBo8N9SpP7ExxZF8xbXrjHaPPYsty5Pw8eh+yL11A4O99gtcfwcr8/JFLB8/DDOH9MTM\nIc9i5pCeuJOfW4XvivzB/kTwaarymyYhxDkAKVLKteUsexnK1MD3pZTLnJZHAVgL5b4rO5RELFFK\nWeipnoqoDVMEKXB92nAEri6LuM+/ea61YYogBe6h+pGh3gUKoYbR/49f7URtmCJIgevb1vN0a6ob\nvPUnqjTBqsmYYNVtTLDqNiZY5A8mWHUbEyzyBxOsus1bfyLkUwSJiIiIiIhqCyZYREREREREQcIE\ni4iIiIiIKEiYYBEREREREQUJEywiIiIiIqIgYYJFREREREQUJEywiIiIiIiIgoQJFhERERERUZAw\nwSIiIiIiIgqS+0K9A0ShsP+qKdS7QCE08OEYv8plmW1VvCdUk928Zwn1LlAIvdKhUah3gcLAX6/l\nhnoXKIT6t2/ocTlHsIiIiIiIiIKECRYREREREVGQMMEiIiIiIiIKEiZYREREREREQcIEi4iIiIiI\nKEiYYBEREREREQUJEywiIiIiIqIg4e9ghblimwWbk5OQk3kd7R59Gv0SJ3ktm5N5HYc3rUFOhkRs\ns5YYOjEJEVpdpWIUOjz25K9iqwUbk2c5zpU/jpnstWxO5nX8dWMKsjMkHmrWEsMmzXY5HzYlJ6HI\navZYT/rP5/HXjWtwJ9+EbvEJeGHYmCp9X1S+YpsFm5fPhlE99n3fnOi1rDHzOg5tToUxQyI2TmCI\n0+fdV4xqh2KbBVvUc6WtH+fKYafzYbCf54Mx8zq2rpiNIqul3G1Q9Slyuka09+MacdDpGjHc7Rqx\nUb1GuNfja73aKOgjWEKI80KIN4Ndb1XXHa52r16K5g93xfR1e2G323FoY4rHckrDmYQXho/D9PX7\n0KhxM+xevaRSMQotHnvy186UJWjeoRtmrt8HADi4wcu5YrVgU3ISer/2FmZ9uR+NGjfHztWLHfFd\nKUvx5qxkvP/nLSjIM2L3mmWOWE7mdexZk4zh783BzPX70O25hKp9U+SXPSlL0bx9V3z0RZrSTmxa\n47Fcsc2CLStm44VhY/HRur2IadIce1KWlBs7d2w/5o/qi/mj+yn/qv+Zbt2otvdIwVFyrnz4RRpg\nt+Owj3Nl64rZeH7YWHzodj44O3d0H2YOeRbFNqtjWVrqMrwxYxkmrdqEgjwj9qYmV9n7If/tTFmC\nFh26Ydb6fbDD+zVCScSS8OJrbyHpy/2IbdwcO5yuETtTliJxVjKm/nkLbucZsUu9RpS3Xm3EKYJh\nrNhmQcaVi3giYTAA4IXhY3Hu6H6PZSO0eoyasQwxjZsBAJq17wLTrfRKxSh0eOzJX8VWCzIuX0QP\n9VzpPWwszh7d57FshE6P0TOXoZF6zJs/3AXGm8oxv3z6FJq374IHftcQEVod/jjmPZd6dqUsRe/X\nxuGB3ym/al+/QUxVvi3yg9JO/IgnEgYBAJ4fNgbnfbQTb0x3+ry36+xIknzFuvbsg8mfbsbkVZsw\n+dPNeGthCuo/2MhRlsJDsc2CzCs/4nH1XOlVzrky0ul8iHM6H5zrM91MB6BxLLt65hTi2nXB/Wob\n0i9xEs4f87wNqj5FHq4RZ7xcIyJ1erzp5zVigNM1wtd6tRUTrDCWow7Nl4jQ6lFss7p8W+TsAacO\nz+UfTiKuXedKxyg0eOzJX9mZbueKzve5Ut/tmDdTj3m7R57C038cVlruQaVcsc2K23lGGG+mo233\nHlXxFihAORkSsU1bOF6X3040dPx95fQpt7bAeyxCq3P8d3hjCnpxamjYqcy5ctXtfACAwxvXoOtz\nfV2Wten+FHr0f9WpjtI2hEInx+0aEVmBa8TPP5xEc6drxDNerhG+1quteA9WGCvIMyFSq3dZFqHV\noSDfiEaNm3tcJ+PyBZw9sg+mW+l4e+GaoMSo+vHYk78K8oyez5U8Ixo18Xyu3Lh8AWeO7IXxZjre\nWZTqsl6JnMzrADSI0OqQnfEr6j8Yg1Npm3H2yD5AAwybNNtr/VQ9CvJNiNCVPfZ38k1eR5gyLl/A\nuaP7YLp1A28tSPE7Bij319zJz0Vc207BexNULe4E8VwpyDM6rWcvU2cJo1MbQqFzO8BrxGn1GjHe\nj2tEeevVRlU1gtVFCLFNCFEghEgXQnQsCQghEoUQN5xiPZ1i54UQU4QQh9X4eSFEY08bEEI0Vcu8\nV0XvISxF6g0+4wV5Jmg0GkTo9LBZCoMSo5qBx578pdVH+YwX5BmhgQaROj1sZs/H/OSejej92jhH\n+YI8I7T6KEz5dBO6xSdgJ+/Xq5HKbSfyTYBGgwith7bARwwADm1OxfPDxgZ1fyl0yjtX7uQr14ZI\nrR5FTufD3rXL0cuP8+DbtE08X2qo8q4Rt/24RpzYsxEvqteIiqxXW1RVgtUZwGgpZX0Ax9T/StwG\n0FGNLQKw3W3dDwC8rMahlnEhhIgGcBjAfCnl0mDvfLiI1BtQZLO4LCuymH2u0zW+D4ZMnIUe/V7F\n+rmTgxKj6sdjT/6K1EeVOVfKS5S7xSfg1UlJeKr/MHzh4Zhf/uEkim1Wx5z9SH0UInUGdO35EgDg\nqX5DYbx5nVN/QkyrN6DYWsF2omcfDJkwCz36D8WX897zO1ZktcCYeR1N23YEhZ/IAM6VLj37YPCE\nWXjS6Xy4cvoUNEC59+BdOX0K/7RZHfd8UehoA7hGdI9PwLBJSXi6/zCs9XCN+NntGuHverVJVSVY\nW6WUZgCQUo4DcL8Q4ln19S6n2Fo11sFp3W0lcQBbAdzvVnczABcAHJFSLkM5hBBj1JEwl/8q9/Zq\nhkid67dGgHJjqftQrydtH3kKd/JNuJNvClqMqg+PfXDVxXbCfTqQJ+0eeQoF+UZl5EKVk3kdp9I2\nYfT00u+26j8Y45hvXyJCq0dBnrGSe0+VEaHVl+kkF9ssiPCjnWjTveTznutX7Pyx/YhrV7unBtbm\ndqLy50ou7uTnIvPyBeRkXsfHo/vh41HKPVjJ77yK88f+4ihvzLyOv6VtxoiPOMpdE1TVNeLN6d7H\nPzytV9tU1z1YmQCaAjiujj5NAxCvxuxuZTPcXtd3ez0FwEWn9X2SUq4BUObGkR0/mdy3G3Zi4wQK\n8kpPzoI8IyJ0BpcHEzhi+SaXGwyLrGaUPN0n0BiFDo99cHlrJ3b/nBv27cRDTV3Pldt5RkTqDB6f\n8leQZ3JJlNyPeZHVjN1rliJx1gqX9X7boJHLNgDlxub6DzYK0rugQMTGCZcOTGk70bBM2bKfdwu8\ntwWlMee6H4prGdw3UMN4aye2XTKGfTtRkXPlTr7J5VpT5DTy1TdxEvo6/SbjzCE9MfnTzfhNpNZR\ndm9qMt6Yycez1xSxQb5G7FqzFGPcrhHlrVcbVddTBJsCOKcmVzcBnJFSdpFSdkHF/w+nSCm7Argp\nhFgd7B0NJxFaPWLjBM6pjzn9Nm0zusWX/vZMQb4Jxeqw7508IzYnJzka0FO7N6FZ+854oEFMhWNx\naoxCh8ee/BWhU86Vs87nitNvVBXkmRxTgwryjdiYPMtxsT25eyOate/suNBuSk7Cq5NmOzpLztto\n9+jTOJW2GQBwKm0T2j3yFG9eD7EIrR6xTVs4Rg++27sFXeP7OOLu7cSW5aWf92/3bFTbgoYeY3Ht\nOrl0vgvcOt0UXtzPlb+5nSt3nM6VAvV8uOPjfChlh91emn9uXTEbgycmlWlDKHQi3a4Rp9I2o7vb\nNaLI6RqxwekaccLtGrExOQnDPFwjyluvNqqqEayuJX8IIRYByJBS/iSEaAIgGsCPamxgAHUfVf99\nBUCmEGK7lPKYrxVqs6ETk7A5eRYObVyDdo89g16vJjpihzak4KFmLfFk3yGIa9cZxTYrNifPwp38\nXMTGCQydmAQAAccotHjsyV/DJs3GxmUz8dcNKWj/2DN44dXSx2gf3Lgav2/WCj36DkEz9ZhvTJ6F\nO/kmxMYJDJs0G4DyGyc3Ll/Ekn8vecyyHYAGUz7dhPoNYtB72FhsTJ6FU3s2uaxHoTVkYhI2L0/C\noU1r0O7Rp9FraGk7cXhjCh5q1gpPJAx2fN6VjnMuYpu2wBC3tsBTrMRdD0+ho/AyeGIStixPwmH1\nXHnO6Vw5VM65MtjrtcH1d7AyL1/E8vElj/JW2pCJn2z0kpxRdRk+aTY2LJuJgx6uEQfUa8RTTteI\nDU7XiOFu14jFbteI9z/d5HO92krj/M1CMAghzgEogPKpagplyt9YKeUtNb4VSnKUAWAHgPcBdJZS\nXlLX3Vry4AohxBQAg9QRq5K6F0gpd6mvX4YyXN9ESlmhx5HUhimCRBSYgQ/H+DVyXhumCFLg/udf\n/wr1LlAIvdKhkV/tRG2YIkiB+3/r8Sdl67L+7Rt6bCeCnmCFCyZYRHUXEyzyBxOsuo0JFvmDCVbd\n5i3B4llBREREREQUJEywiIiIiIiIgoQJFhERERERUZAwwSIiIiIiIgoSJlhERERERERBwgSLiIiI\niIgoSJhgERERERERBQkTLCIiIiIioiBhgkVERERERBQk94V6B0KlT5uYUO8ChdD+q6ZQ7wKFgY6N\n7g/1LlAI3bX9d6h3gcJA37aNQr0LFELHZX6od4FqII5gERERERERBQkTLCIiIiIioiBhgkVERERE\nRBQkTLCIiIiIiIiChAkWERERERFRkDDBIiIiIiIiChImWEREREREREFS5QmWEOK8EOLNqt5OXWU2\nmzE2cRR6PNYd8+bMCrhsoDEKnWKbBevnvYd5o/oiLTXZZ9mczOtK2TcSsH7+FBTbrJWOUfiwWsyY\nNmEsBvbugU+WzPNrne0bv4TVanFZli5/wchBfSpUD4WWzWrB/Kl/wugBPbF25QKfZTPTf8X4Ef09\nlq1IPRSe2J+ou4qsFnw+exI+ev0lbE9Z6rNsVoZUy76I1XMmufQL/Knn+J5NdaIvwRGsMDdn1nQ8\n9vgT+Pb7M7Db7ViR7P2D4atsoDEKnd2rl6L5w10xfd1e2O12HNqY4rFcsc2CLcuT8MLwcZi+fh8a\nNW6G3auXVCpG4WX5ojno3P0x7Dj4Lex2O774fIXP8t+dOOKxzMpFc7DokzX4ascBmHKysHLx3DJl\nDqTtwAtPdCiTnFFopCTPQ/suj+KLXcdgt9uxae0qr2VTl8/HjMWfY9U3acgzZiN1xcd+1TP+9X4Y\n8nw3DOnVFUOe74YV86ZV6XuiqsH+RN219fPFaNmhG+Z//RfY7cC+b1Z7LFdkteDrZbPQ9/W3Mf/r\nA4ht0gJbPlvkdz2Xvj+B/V7qrm2YYIUxs9mMM6dPY8TIUQCACZOmYOf2bRUuW1hYGFCMQqfYZkHG\nlYt4ImEwAOCF4WNx7uh+j2UjtHqMmrEMMY2bAQCate8C0630SsUofFgtZlw6fwYDh44AALz59gQc\nSNvptfy8GVNwIG0HNBqNy/LvThxFp66P4MGGjaDT6fHu+zNwcK9rPVaLGenylzLrUmjYrBZc+fEc\nEl4ZDgAYljgeRw/s9lj2zHfH0K5zd/zuwRhodXokTvgQx9SyVovZZz1WiwXrd5/AlsPnsOXQWUyY\nzhGucMP+RN1VZLUg/ecLeKbfEABAwmvjcPrIXo9lI3V6vJW0HLFNlH6BeLgLcm6mq/WYfdbz5dKZ\n+OHIPqCOXB+YYIWxa1evoHWbto7XBoMBFosZFkvZb459lf3l2tWAYhQ6ORkSsXHC8TpCq0exzep1\n2P2BBjGOvy//cBJx7TpXOkbh4fqv19CiZWvHa53eAJvV4nWEafrcJViwIgV2u91l+ZPPxGPw66Md\nrxs2eggAXOpZ+9kK9On/SjB3nyohQ15D0xatHK+1Oj1sVgtsHo599yd7ov+QkY7XDWJiAShJWub1\nX8rWYzG71ON+vlB4YX+i7srK+BW/b1ban4jU6VHkoz9R36lfcOn7kxDtu6j1SJ/1jHxvDt6alQzU\nkbbivureoBAiGsAiAIMA3AawQ0o5zSmeCGAqgPpqfJyU8pgaOw9gK4DnAHQBkAlgoJTyVnW+h5oi\nOysLhiiDyzK93oDsrCy0bNWq3LIGQxSys7IqHPO2Dao+BXkmRGr1LssitDoU5BvRqHFzj+tkXL6A\ns0f2wXQrHW8vXBOUGNV8JmM2dHrXz7BWp0duTjbiWrSsUF06Xek5VzJSVbLMlJONPFMO4lq0ZGe7\nhsjPzfF47PNNOWjs1BFyjpXITP8V0GiU8p7q0Rsc9dhhx/I5U5GR/gvad+rOEawwxP5E3XU7z4hI\nretxidTqcDvPiNgmnvsT138+j+8P70XOzXRMXrI24Hpqs1CMYB0DUCClrC+lbA4gTgjhPCHzNoCO\nUsr6UBKx7W7rfwDgZTUOtQypoqOj/S4bFRUVUKwi26DqE+nWAXJXkGeCRqNBhE4Pm6UwKDEKT4ao\nyn+Gt25Yh9FvT3C8/mTJXIx+e2Kl66WqpTd4b9udpW35EsPeHO9XPRpo0LRFa6zbdRw6vcHl3i0K\nX+xP1F1ave924naeERpoEKn13S8or57arFpHsIQQ8QCipZQfOi1OBHBHCPG+lLJQSrmrJCClXCuE\nWCOE6CClvKQu3ialNKt/bwUQX842xwAY4778p6uyUu+lJoiOjoa50Oyy7N69exUuG2iMQidSb0CR\nzXVaRZHF7KW0omt8H3SN74Mrp09h/dzJmLxqU6VjtYW3duLQf/wUgr0JLoMhGla3c8NcWLnP8Hcn\njsBmMTvu6/ruxBFoNBrENS87KkKhozdElTn2FnP5X5Kc/vYobFaL456r8upZ8Nk3aNCwEQCg3+AR\nGD+iPxInfIjahv2J8suyPxF+tPooFNlcj0t5X6Y++lxfPPpcX/z0w0l8njQRH322JaB6arPqniLY\nEcq0Pgcp5T0hBKBM+TuuTiGchtLEyX2uSYbb6/rwQUq5BkCZeU3F/1Om3rBjiIpC4b27LsvM5sIy\nQ/DllQ00RqETqdOjyK3hKrZZykwb9KTtI09hy/Ik3Mk3udxjVZlYuPPWTtz6z+Kwbyf0BgPMha7n\nitVihs4Q2Gc4Xf6CbRvWY9UXpYn2xXOncf3XaxjYu4djeuCIgS9i9FsT0LvvgMB3nipFqzOUSahs\nFjO0Pka7M9N/RdrWr7Hgz1/7XU9JcgUA+qhoQKOBzWpxmXJYG7A/UX5Z9ifCT6ROD5vZNTEqsloQ\n6cfn9+FHn8ZXS2eiIN9UqXpqo+pOsDKhJFIOQoj7oSRR59Tk6iaA0VLKD9T4v6p5H8NG6zZtkZ2d\n7XidnZWFqKhoxMY+VKGyUVHRAcUodGLjBAryTI7XBXlGROgMHhOfgnyTy02pRVYzAE2lYhQ+WrRs\nDZOx9DNsysmG3hCFhupDDLzx9CRAi7kQnyyei0WfpLosf/f9GXj3/RmO172f7IivdxyEVqer5N5T\nZcSJ1sg35The55myodNHuSREzqwWM1JXfIyZSz4PuJ5c9VyrbclVbcf+RN31+7iWuJ1ndLz+z1wj\nInUGl+t/idt5Rvz2wdLPfZHV7HgqoFJPTvn18CmCwSel3AmgQAjxOeBIrrYB2K5O+6sPIBrAj2p8\nYHXuX7gxGAxo3aYtdu1QblNbvy4VAwcNdsSzs7NgVr9N8FU20BiFToRWj9g4gXPHlEezf5u2Gd3i\nExzxgnwTitUphHfyjNicnISCfCUhO7V7E5q174wHGsRUOBanxih86PQGtGjZGgf3KrOvt21cjxf7\nlTatucbsMtO/AM9PhZs/Ywo+mrek3MTJbrfDHv5f6oc9rU6Ppi1a4diBPQCAvVu/RvxLpSOK+aYc\nlycBrpj7ASbOWIhIrc7vei5fPIv5U//kqGfz2lXoN2hElb4vCj72J+quSJ0ev28mcPrIPgDKDwE/\n1quvI347z4gi9fN9O8+IL5fOdCRkR3duQIv2nVG/QYxaT0uv9TjUkYcgVUeC5f5/sjOA3wohCqBM\n9zsvpRwCAFLKmwB2AMgUQqSrZe0+6qrzli5fiUOHDqLHY91RT1MP4ydMcsRWJi/Frh3b/CobaIxC\nZ+jEJFz54STmjeoLTb166PVqoiN2aEOK43ex4tp1RvvHn8Xm5FmYN6ovTH+/gSETkwKKDVVjFF4+\nmrcU3x4/hIG9e6BevXoYNa704QVrP1+JA3sdt75i5eK5ePmFJ6HRaDBi4Iv4cOI4AMrvYF26cBZv\nDOqD3k92xAtPdEDvJzsi12lkowR/B6vmmDhjIU6fOoLRA3pCU68eho7+kyO2ce0qx29dnfnuGC5f\nOofxI/q7/Ghwfq7RZz3tOnVDu87d8e+v9cXoAT3RtEVrl21Q+GB/ou4a+d5c/Pj9CXz0+kuop9Hg\npeFjHbF936x2JE0t2ndBpyd64sulM/HR6y8h51Y6Rr431696tq1eio9efxHQaDB33CCsnlO7j72m\nrj5OtzbMmabA7b9qKr8Q1VoDH47xKwOoDfdgUeDu2v471LtAIdTh3wx+tRPsT9Rtx2V+qHeBQujF\nNg08thP8oWEiIiIiIqIgYYJFREREREQUJEywiIiIiIiIgoQJFhERERERUZAwwSIiIiIiIgoSJlhE\nRERERERBwgSLiIiIiIgoSJhgERERERERBQkTLCIiIiIioiBhgkVERERERBQk94V6B4iIaqp7tv8O\n9S4QEVENlmsrDvUuUA3EESwiIiIiIqIgYYJFREREREQUJEywiIiIiIiIgoQJFhERERERUZAwwSIi\nIiIiIgoSJlhERERERERBwgQrzJnNZoxNHIUej3XHvDmzAi4baIxCp9hmwfp572HeqL5IS032WTYn\n87pS9o0ErJ8/BcU2a6VjFD5sVgvmTf0TRg3oidSVC3yWzUz/Fe+M6O+xrK96fK1HoWOzWjB/6p8w\nekBPrPXj2I8f0d9j2YrUQ+GJ/Ym66582K7YunIqV4wbg0PqVPsvm3kxXyo4dgK2LPsA/K9AvuHXl\nIr6a8TZWjhuAU1u/qOxu12hMsMLcnFnT8djjT+Db78/AbrdjRfLSgMoGGqPQ2b16KZo/3BXT1+2F\n3W7HoY0pHssV2yzYsjwJLwwfh+nr96FR42bYvXpJpWIUXlYnz8PDXR7Ful3HYLfbsXHtKq9l1yyf\nj5mLP8en36Qhz5iNNSs+9qseX+tR6KQkz0P7Lo/iC/WYbfJx7FOXz8eMxZ9jlXoMU52Ooa96xr/e\nD0Oe74YhvbpiyPPdsGLetCp9T1Q12J+ouw6uTUaT9l3w7updgN2Ok1vWeiz3T5sVaavm4ZmhY/Bu\nyi48+IdmOLhW+YL30okDWDl2AFaOG6D8q/6X9/cbAJTE7NC6lej/7iy8u3oXOjz7UrW9v1BgghXG\nzGYzzpw+jREjRwEAJkyagp3bt1W4bGFhYUAxCp1imwUZVy7iiYTBAIAXho/FuaP7PZaN0OoxasYy\nxDRuBgBo1r4LTLfSKxWj8GGzWnDlx3NIeGU4AGB44ngcPbDbY9nT3x1D+87d8bsHY6DV6TFmwoc4\nppa1Wsxe6/G1HoWO+7Ef5uPYn/nuGNo5HcNEH8fevR6rxYL1u09gy+Fz2HLoLCZM5whXuGF/ou76\np82Kv1/7Ed1efAUA8PSQRPx04oDHsr/R6jBk2iI0+EMcAKBx207IVxOoDs+8iHHLv8G45G8wbvk3\nGDH3z7i/QQwe/IPShzi0bjmeGZqI6P/vQQBA9O8aVvVbC6n7Qr0DFLhrV6+gdZu2jtcGgwEWixkW\niwV6vd7vsr9cuxpQzH0bVH1yMiRi44TjdYRWj2KbFcU2KyK0ujLlH2gQ4/j78g8nEdeuc6VjFB4y\n5DXEtWjleK3V6WGzWmCzWqDVuX6GH3myJ9p36u543SAmFoDSUc+8/ovXenyt574Nqj4Z8hqa+nns\nuz/ZE+18HPsy9VjMLvXY7faqfCtUxdifqLtMmRINm7RwvP6NVod/2qz4p82K33joTzgnRvLst/hD\n204u65Y4uDYZTw95EwBwN9+EvFsZaNH1iap4CzUSR7DCWHZWFgxRBpdler0B2VlZfpU1GKKQnZVV\n4Zi3bVD1KcgzIVLrekGK0OpQkG/0uk7G5QvYnJyEzCsX8fywsUGJUc2Xl5sDrd71M6zV6ZFvyvFY\n3rnjnZn+K6DRQKvTl1uPt/UodPJzc6ALwrH3WI/e4KjHDjuWz5mKUQOe5fTAMMX+RN119x+5iHDr\nT/xGq8Pdf5i8rnPrykXs+WQu/n71Rzw9+M0y8dyb6bj3j1z8oU1HZRv5JtzfoCHO7N+GlEkjsGby\nCMfUwdrKrxEsIcR5AFsBPAegC4AMAGMADFb/tQP4QEqZqpaPBrAIwCAAtwHskFJO81FfJoCBUspb\nTuunAugJoADAIinlWiHEagBNpZS9nOp6H0BPKeXzAf4/qFWio6P9LhsVFRVQrCLboOoT6dYBcleQ\nZ4JGo0GETg+bpdBlpCvQGIUnvcH759vZni1fYvib4ytcT3nrUej4e+zTtnyJYX4eew00aNqiNT5a\n9GekrvgYqSs+RuKEDyu9rxRa7E/UXRE63/2Ju//IhUajwW+0ehRZCsuMdJ3auhZPD010KX8n34QI\nvQFjk7/Cmf3b8Ne1yRgx97Mq2f+aoCIjWB8AeFlKWR/AHQAXAJxRXy8EsNqp7DEABVLK+lLK5gDi\n1OTIW32AkpA5r79FSvlbKAnYOCFEY7VMTyFElFs9CyvwPmqN6OhomAvNLsvu3btX4bKBxih0IvUG\nFNksLsuKLGYvpRVd4/tgyMRZ6NHvVayfOzkoMar59IYo2NzODYu5sNz1Tn97FEVWi+O+G3/rcV+P\nQkdviII1wGNvczv2vupZ8Nk3GDr6TwCAfoNH8P67MMT+RN0VqTOg2K0/UWz13Z/o8MyL6PfOdDyS\nMAcYqJUAAAqPSURBVARbF37gtq4FubfS8YfWHVy2EaHT4+GnewMAuvcZhNxbNyr0BMJwU5EEa5uU\nsuT/+BEAd6SUJa3oDgAQQkQJIeIBREspnb++SgQwxi0xcq5vK4D71TriAXQCsEgIcQNKIhcNIF5K\neRNK8jXNqaxdSnnC204LIcYIIc67/1eB911jGaKiUHjvrssys7mwzBB8eWUDjVHoROqUb42cFdss\nZaYNetL2kadwJ9+EO/llh/8DjYW72txO6HSGMp1qm8VcZrqfs8z0X5G29Wt8tPDTCtXjaT0KHW2Q\njn159TRo2MixXB8VDWg0sFldO2y1QW1uJ9ifqLt+o9Wh2O0LlGKbpcy0QU9Etydx9x8m3PtHrmPZ\nTycOoHGbTi7l7m8Qg/t/F+OyLEKr9zkNMdxV5CEXGW6vM53+LnD6u6NbDFLKe0IIQBmNOu6lvpKR\nrCYAjviY8rcIwDYoSdYYAJ6fTV267TUA1rgvL/4fhP0dua3btEV2drbjdXZWFqKiohEb+1CFykZF\nRQcUo9CJjRMoyCttmAryjIjQGVweSuGI5ZtQ32l5kdUMQFOpWG3jrZ346f+aw76diBOtked0z02e\nKRs6fZRLp9iZ1WJG6oqPMXPJ5xWqx9t6FDpxorXL/VaVOfb+1pNrVK4XtfH+O/Ynyi/L/kT4iWkq\nXBKdu/kmROj0Hp/yp9xLVdovKLZaoHHrF9zNN6JhU+Gy7P4GMWWSqX/arGWSrtqkKh5ykQklkXIQ\nQtwP5T6tc4Gs70xKeQxAgRCiJ5R7tOrk9EBAeQJP6zZtsWvHdgDA+nWpGDhosCOenZ0Fs9lcbtlA\nYxQ6EVo9YuMEzh1THs3+bdpmdItPcMQL8k2OIf87eUZsTk5CgTrydGr3JjRr3xkPNIipcCxOjVH4\n0Or0iGvRCscO7AEApG39GvEvDXDE8005LqMNy+d+gIkzFiLSbU59efV4W49CR6vTo6nTMdtbzrFf\n4ePYe6vn8sWzmD/1T456Nq9dhX6DRlTp+6LgY3+i7vqNVoeGTVo4Hs1+Zv9WdHim9Deq7uabHFP5\n7uabsOeTubir9gtO79uMP7Tt6JKMlTzQwn0bLbs/hTP7tzm2Ibo96fEphbVFMBMsDQBIKXdCSYA+\nBxzJ1TYA252mBHqlJlCZQoitJcuEEC8LITo4FVsEYCqA81LK8ieU12JLl6/EoUMH0eOx7qinqYfx\nEyY5YiuTl2LXjm1+lQ00RqEzdGISrvxwEvNG9YWmXj30erX0htJDG1Icv4sV164z2j/+LDYnz8K8\nUX1h+vsNDJmYFFBsqBqj8DJxxkL8cOoIRg3oiXr16uFV9X4ZANiwdpXL71ldvnQO74zoj8HPd8Pg\nXl0x+PluyM81+qynvPUodCbOWIjTp45g9ICe0NSr57hXCgA2rl3luF/qjHoMx4/o7/Kjwc7H3lM9\n7Tp1Q7vO3fHvr/XF6AE90bRFa5dtUPhgf6Lu6v/ODPx65hRWjhsAjaYenho82hE7uWUtLqnJV+O2\nndDq0aeRtmouVo4bgLy/Z6D/OzNc6rrn4amEAPD04Ddx68oFrBw3ALeu/ogXRk+s2jcVYhp/frtC\nCHEOwFYp5VL19RQAg6SUXdXX0VCmCT4gpSxU77VaCyAeyshVivM9WX7U577+UQCJzsmUEOJfUJ4e\n6PX+K19qw5A+BW7/1do775fKN/DhGL/mOtaGKYIUOB78uq3Dvxn8aifYn6jbNv34f0O9CxRCo7r+\nm8d2wq8Eq6ZRR8XOqU8oDAgbxLqNCVbdxgSL/MGDX7cxwSJ/MMGq27wlWOH6Q8MfoJyHWxARERER\nEVW3ijxFMOSEEIlQ7r86K6V8IdT7Q0RERERE5CysEiwpZSqA1FDvBxERERERkSfhOkWQiIiIiIio\nxmGCRUREREREFCRMsIiIiIiIiIKECRYREREREVGQMMEiIiIiIiIKEiZYREREREREQaKx2/kD5HWR\nEGKMlHJNqPeDQoPHn/zB86Ru4/Enf/A8qdt4/D3jCFbdNSbUO0AhxeNP/uB5Urfx+JM/eJ7UbTz+\nHjDBIiIiIiIiChImWEREREREREHCBIuIiIiIiChImGAREREREREFCROsuotPfKnbePzJHzxP6jYe\nf/IHz5O6jcffAz6mnYiIiIiIKEg4gkVERERERBQkTLCIiIiIiIiChAkWERERERFRkDDBIiIiIiIi\nChImWEREREREREFyX6h3gDwTQiQCSAFQ8phHjfqv82s7gAeklIWV2M4NANullNMCrUOtJxrAIinl\nuMrUQ+Fz7IUQTdT97ALgNoDFUsrUQPeHKi5czhWnethOBEm4HHu2E6EXLueKUz1sJ4IkXI59bWwn\nmGDVUOqJ5Ti5hBAvA9gmpfw/Qd7UGACZlalACNEUygfjX0HZozoujI79EQCJUsoTQoieALYLIexS\nyrXB2T0qTxidK2wngiyMjj3biRALo3OF7USQhdGxr3XtBBOsOk5Kebwy6wshFgKIx//f3r3kNg2F\nURw/XQAU2gXwEjpjoGIBUFgACMScRyXmPMQGmDCnHTDnKeaIwAIIMP4kWrEBIlDHEAZ2kBUSSFrH\nvrb/v0krx76N+3050s21E2lZ+wxWVGs/tbd9StJ2RLzPx+rZfijpnqTGBiImIye6i5zArMiJ7iIn\n/sY9WNiXiLgfEWuSenU/F1QnIj5L2hjbvCPpeA1PB4kjJ7qJnMA8yIluamtOsILVcKNrlSVdVXbd\n6sviNbC2+5L6klaUvTM0kHQlb+jR45vFZVjbW5KuKLsuty9pIyK+VnJCmFndtZ+w/aykT2WcG8pV\nd6+gPnXXnpxojrp7BfWpu/ZtzAlWsJqvJ2kQESsRcVLSCdubY/uckXQ9IlaUNezbaYPZ/ijpp6Qj\nEbGq7AWHNCVTe9uHJN2UdHfOc0A1kukVVC6Z2pMTyUumV1C5ZGrflpxggtVg+Y2AyxHxoLD5pqRb\ntg8Wtj2LiF1Jioirkg7bPjdhvHVJRyPidmH/d7zblJ4Ea/9WWfC+38PpYIES7BVUJMHakxOJSrBX\nUJEEa9+KnGCC1WynNXYjaET8yH9d+8dx065tPTY+HpKVTO1tv5H0OCJe7+V4LFwyvYLKJVN7ciJ5\nyfQKKpdM7duUE0ywmm1HY82fL60OJX34x3HHJW1PGa/RNxV2SBK1z8PwWUQ8mfdYVCaJXkEtkqg9\nOdEISfQKapFE7duWE0ywGiwiXkka2H4s/XlBPFf2ZW+7hV0v2F62fcj2C0lfJi29RkRP0s5ovHzM\ny5OWgCdY+v8uKEsKtc/He96WMGyrFHqlgJyoUAq1JyeaIYVeKSAnKpRC7duYE0ywmu+MpFXbA2Xv\nJPQj4trYPt8lvVD2qS8HJF0sPDYc2/e8pCXbA9vflH2izNSlXtt38r99Q9K67W/Ovr8Ai1db7Z19\nb8UlSVu2f9n+Ofq577PCIpAT3UVOYFbkRHeREyVbGg7H/ydoE2cfnfk0Ih7V/VxQLWqPWdEr3UXt\nMSt6pbuo/fxYwQIAAACAkjDBaj+WKLuL2mNW9Ep3UXvMil7pLmo/Jy4RBAAAAICSsIIFAAAAACVh\nggUAAAAAJWGCBQAAAAAlYYIFAAAAACVhggUAAAAAJfkNa3hHdwWjgKgAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<matplotlib.figure.Figure at 0x119e94048>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "fig, axs = plt.subplots(1, 3, sharey=True)\n",
    "# with sns.axes_style(\"white\"):\n",
    "sns.heatmap(phi_actual, vmin=0, vmax=1, cmap='Blues', ax=axs[0], cbar=False, annot=True, fmt=\".3f\", annot_kws={\"size\": 14})\n",
    "axs[0].set_title(r\"$\\phi_{Original}$\")\n",
    "sns.heatmap(phi_orig, vmin=0, vmax=1, cmap='Blues', ax=axs[1], cbar=False, annot=True, fmt=\".3f\", annot_kws={\"size\": 14})\n",
    "axs[1].set_title(r\"$\\phi_{Start}$\")\n",
    "sns.heatmap(phi, vmin=0, vmax=1, cmap='Blues', ax=axs[2], cbar=False, annot=True, fmt=\".3f\", annot_kws={\"size\": 14})\n",
    "axs[2].set_title(r\"$\\phi_{End}$\")\n",
    "\n",
    "\n",
    "fig.set_size_inches((12, 3))\n",
    "\n",
    "for ax in axs:\n",
    "    ax.set_xticklabels(['Topic 1', 'Topic 2'])\n",
    "    ax.set_yticklabels(vocab, rotation=360)\n",
    "\n",
    "fig.tight_layout()\n",
    "# fig.savefig('phi_start_end.png', dpi=300)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "matplotlib==1.5.1\r\n",
      "numpy==1.10.4\r\n",
      "seaborn==0.7.0\r\n"
     ]
    }
   ],
   "source": [
    "!pip freeze | grep 'seaborn\\|matplotlib\\|numpy'"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
